const STRINGS = {
  en: {
    "loading.coreBoot": "CORE BOOT",
    "loading.initializing": "INITIALIZING OPERATOR CONSOLE",
    "loading.coreOnline": "CORE INTERFACE ONLINE",
    "loading.firstShift": "YOUR FIRST FUSION SHIFT",
    "loading.shiftLoad": "SHIFT LOAD",
    "loading.preparing": "PREPARING OPERATOR CONSOLE",
    "loading.loadingShift": "LOADING SHIFT",
    "loading.returning": "RETURNING TO OPERATOR CONSOLE",
    "loading.restartingShift": "RESTARTING SHIFT",
    "loading.resettingCore": "RESETTING CORE SESSION",
    "loading.shift": "SHIFT",
    "loading.textures": "Loading textures",
    "briefing.prompt": "ENTER — HIDE · Q — DROP",
    "results.report": "SHIFT REPORT",
    "results.profile": "OPERATOR PROFILE",
    "results.awaiting": "Awaiting shift data.",
    "results.outcome.complete": "COMPLETE",
    "results.outcome.failed": "FAILED",
    "results.title.qualification.complete": "QUALIFICATION PASSED",
    "results.title.qualification.failed": "QUALIFICATION FAILED",
    "results.summary.qualification.complete": "All scheduled load phases completed. Operating parameters remained within accepted limits.",
    "results.summary.qualification.failed": "Qualification requirements were not met. Review the recorded operating metrics before repeating the shift.",
    "results.comment.qualification.complete": "Operating parameters remained within accepted limits. Operator is cleared for subsequent assigned shifts.",
    "results.comment.qualification.failed": "Qualification requirements were not met.",
    "results.title.reliability.complete": "INSTRUMENT CHECK PASSED",
    "results.title.reliability.failed": "INSTRUMENT CHECK FAILED",
    "results.summary.reliability.complete": "The operating shift was completed under unreliable instrument and control indications.",
    "results.summary.reliability.failed": "Instrument-reliability requirements were not met. Review the recorded events before repeating the shift.",
    "results.comment.reliability.complete": "Operator maintained a safe operating state while cross-checking unreliable indications. Instrument reliability assessment is complete.",
    "results.comment.reliability.failed": "Instrument reliability assessment was not completed.",
    "results.title.cost.complete": "COST TRIAL PASSED",
    "results.title.cost.failed": "COST TRIAL FAILED",
    "results.summary.cost.complete": "Required grid output was maintained within the accepted limits of the low-cost fuel trial.",
    "results.summary.cost.failed": "The assigned output and operating-cost requirements were not met. Review the recorded metrics before repeating the trial.",
    "results.comment.cost.complete": "The assigned fuel blend remained operationally viable. Output delivery and reactor condition were accepted for the trial.",
    "results.comment.cost.failed": "The operating-cost trial requirements were not met.",
    "results.title.freeplay.complete": "FREE SHIFT COMPLETE",
    "results.title.freeplay.failed": "FREE SHIFT ENDED",
    "results.summary.freeplay.complete": "The ten-minute public-build shift and its variable operating schedule were completed.",
    "results.summary.freeplay.failed": "The free shift ended before all operating requirements were completed.",
    "results.comment.freeplay.complete": "Free-shift record accepted. Additional scheduled shifts remain in development.",
    "results.comment.freeplay.failed": "Free-shift record closed without completion.",
    "results.keyMetrics": "KEY METRICS",
    "results.serviceComment": "SERVICE COMMENT",
    "results.shift.exploring-around": "SITE-12 / QUALIFICATION SHIFT",
    "results.shift.intro-shift": "SITE-12 / QUALIFICATION SHIFT",
    "results.shift.unexpected-stuff": "SITE-12 / INSTRUMENT RELIABILITY CHECK",
    "results.shift.fuel-problems": "SITE-12 / COST OF RUNNING TRIAL",
    "results.shift.freeplay": "SITE-12 / FREE SHIFT",
    "results.schedule.exploring-around": "01.05.2036 / 06:42–06:45",
    "results.schedule.intro-shift": "01.05.2036 / 06:42–06:45",
    "results.schedule.unexpected-stuff": "02.05.2036 / 06:00–06:03",
    "results.schedule.freeplay": "PUBLIC BUILD / 10:00 SHIFT",
    "results.schedule.fuel-problems": "07.05.2037 / 21:40–21:43",
    "results.status.acceptable": "ACCEPTABLE",
    "results.status.reviewRequired": "REVIEW REQUIRED",
    "results.failure.gridCompliance": "Grid-demand compliance remained below the qualification threshold.",
    "results.failure.operatingEfficiency": "The reactor operating balance remained below the required efficiency.",
    "results.failure.peakCoreStress": "Peak core stress exceeded the permitted qualification limit.",
    "results.failure.criticalTemperature": "Critical plasma temperature persisted beyond the permitted duration.",
    "results.failure.coreStall": "Core-stall conditions persisted beyond the permitted duration.",
    "results.failure.instability": "Containment instability persisted beyond the permitted duration.",
    "results.failure.sustainedDemandDeviation": "A severe grid-demand deviation was sustained for too long.",
    "results.failure.phaseTracking": "Too few scheduled load phases met their compliance target.",
    "results.failure.qualityFailure": "Output quality remained below the assigned operating standard.",
    "results.failure.coreDestroyed": "Core stress exceeded the structural operating limit.",
    "results.failure.safeShutdown": "The reaction was lost before the scheduled shift ended.",
    "results.failure.unknown": "The shift ended without satisfying the assigned qualification requirements.",
    "results.stats.shiftTime": "SHIFT TIME",
    "results.stats.avgEfficiency": "AVG EFFICIENCY",
    "results.stats.avgOutput": "AVG OUTPUT",
    "results.stats.maxOutput": "PEAK OUTPUT",
    "results.stats.avgDemandError": "AVG DEMAND ERROR",
    "results.stats.gridCompliance": "GRID COMPLIANCE",
    "results.stats.phasesPassed": "PHASES PASSED",
    "results.stats.stability": "STABILITY",
    "results.stats.warningEvents": "WARNING EVENTS",
    "results.stats.criticalEvents": "CRITICAL EVENTS",
    "results.stats.emergencyInterventions": "EMERGENCY INTERVENTIONS",
    "results.stats.maxTemp": "MAX TEMP",
    "results.stats.maxCoreStress": "MAX CORE STRESS",
    "results.stats.maxHeatSoak": "MAX HEAT SOAK",
    "results.stats.criticalTemp": "CRITICAL TEMP",
    "results.stats.outputSurge": "OUTPUT SURGE",
    "results.stats.overDemand": "OVER DEMAND",
    "results.stats.underDemand": "UNDER DEMAND",
    "results.stats.coreStall": "CORE STALL",
    "results.stats.ventHeld": "VENT HELD",
    "results.stats.ventPulses": "VENT PULSES",
    "results.stats.pulseUses": "PULSE USES",
    "results.stats.avgTemp": "AVG TEMP",
    "results.stats.controlMotion": "CONTROL MOTION",
    "results.profile.containmentPostmortem.title": "OPERATOR TYPE: CONTAINMENT POSTMORTEM",
    "results.profile.containmentPostmortem.summary": "You found the part of the operating envelope that writes reports in all caps.",
    "results.profile.nervousPurgeTech.title": "OPERATOR TYPE: NERVOUS PURGE TECH",
    "results.profile.nervousPurgeTech.summary": "Short purge pulses solved several problems and created several new entries in the logbook.",
    "results.profile.fieldPhysicist.title": "OPERATOR TYPE: FIELD PHYSICIST",
    "results.profile.fieldPhysicist.summary": "Quiet hands, good coupling, acceptable grid discipline. Suspiciously competent.",
    "results.profile.highLoadSpecialist.title": "OPERATOR TYPE: HIGH LOAD SPECIALIST",
    "results.profile.highLoadSpecialist.summary": "You ran the burn hot on purpose and mostly convinced the machinery it was planned.",
    "results.profile.redlinePhilosopher.title": "OPERATOR TYPE: REDLINE PHILOSOPHER",
    "results.profile.redlinePhilosopher.summary": "You treated heat soak as a philosophical disagreement between you and the panel. The panel had evidence.",
    "results.profile.busSurgeConductor.title": "OPERATOR TYPE: BUS SURGE CONDUCTOR",
    "results.profile.busSurgeConductor.summary": "The grid received power in expressive waves. Some of them were even useful.",
    "results.profile.gridOverfeeder.title": "OPERATOR TYPE: GRID OVERFEEDER",
    "results.profile.gridOverfeeder.summary": "Demand was a target. You interpreted it as a lower bound.",
    "results.profile.fuelIntoNoise.title": "OPERATOR TYPE: FUEL INTO NOISE",
    "results.profile.fuelIntoNoise.summary": "A lot of fuel became heat, alarms, and character development before it became grid power.",
    "results.profile.magneticAccountant.title": "OPERATOR TYPE: MAGNETIC ACCOUNTANT",
    "results.profile.magneticAccountant.summary": "Containment was extremely well filed. Net output was less impressed.",
    "results.profile.heatSinkGambler.title": "OPERATOR TYPE: HEAT SINK GAMBLER",
    "results.profile.heatSinkGambler.summary": "You trusted the thermal mass longer than the manual recommends, but the lights stayed on.",
    "results.profile.coolantIntern.title": "OPERATOR TYPE: COOLANT INTERN",
    "results.profile.coolantIntern.summary": "The plasma spent much of the shift wondering why it was being refrigerated instead of operated.",
    "results.profile.underpoweredOptimist.title": "OPERATOR TYPE: UNDERPOWERED OPTIMIST",
    "results.profile.underpoweredOptimist.summary": "The grid kept asking for more. You maintained a tasteful distance from the request.",
    "results.profile.whyIsThisLampBlinking.title": "OPERATOR TYPE: WHY IS THIS LAMP BLINKING",
    "results.profile.whyIsThisLampBlinking.summary": "You made many corrections and at least some of them were related to the problem at hand.",
    "results.profile.controlRoomStatue.title": "OPERATOR TYPE: CONTROL ROOM STATUE",
    "results.profile.controlRoomStatue.summary": "The panel changed phases. You respected its independence.",
    "results.profile.edgeWalker.title": "OPERATOR TYPE: EDGE WALKER",
    "results.profile.edgeWalker.summary": "You visited the red band often enough to learn the furniture, then left before it became permanent.",
    "results.profile.unscheduledExperiment.title": "OPERATOR TYPE: UNSCHEDULED EXPERIMENT",
    "results.profile.unscheduledExperiment.summary": "The shift ended with useful data, technically. The maintenance team may use different words.",
    "results.profile.shiftOperator.title": "OPERATOR TYPE: SHIFT OPERATOR",
    "results.profile.shiftOperator.summary": "You kept the core moving, made some compromises, and left enough machine for the next person.",
    "results.profile.peakOutputTourist.title": "OPERATOR TYPE: PEAK OUTPUT TOURIST",
    "results.profile.peakOutputTourist.summary": "You went sightseeing near maximum output and brought back most of the equipment.",
    "results.profile.reactionPoet.title": "OPERATOR TYPE: REACTION POET",
    "results.profile.reactionPoet.summary": "The numbers formed an emotional arc. The grid requested fewer metaphors.",
    "results.profile.panelApprentice.title": "OPERATOR TYPE: PANEL APPRENTICE",
    "results.profile.panelApprentice.summary": "You learned which lights matter and which lights merely judge.",
    "menu.subtitle": "FUSION CORE SHIFT CONSOLE",
    "actions.startWork": "START WORK",
    "actions.credits": "CREDITS",
    "actions.newShift": "START NEW SHIFT",
    "actions.levelSelect": "LEVEL SELECT",
    "actions.mainMenu": "MAIN MENU",
    "actions.play": "PLAY",
    "actions.profile": "PROFILE",
    "actions.settings": "SETTINGS",
    "actions.back": "BACK",
    "actions.resume": "RESUME",
    "actions.menu": "MENU",
    "actions.restart": "RESTART",
    "actions.continue": "CONTINUE",
    "actions.repeatShift": "REPEAT SHIFT",
    "credits.title": "CREDITS",
    "credits.development": "DEVELOPMENT BUILD",
    "credits.placeholder": "Full credits will be added during production.",
    "levels.route": "LEVEL ROUTE",
    "assignments.heading": "ASSIGNED SHIFTS",
    "assignments.applicationApproved": "APPLICATION APPROVED",
    "assignments.assigned": "ASSIGNED",
    "assignments.notAssigned": "- NOT ASSIGNED -",
    "assignments.nothingSelected": "- NOTHING SELECTED -",
    "assignments.startShift": "START SHIFT",
    "assignments.approved": "APPROVED",
    "assignments.noMore": "NO MORE ASSIGNMENTS",
    "assignments.archiveEmpty": "ARCHIVE IS EMPTY",
    "assignments.completed": "COMPLETED",
    "assignments.operationsSubject": "TERRAGEN SYSTEMS / OPERATIONS",
    "assignments.developmentSubject": "TERRAGEN SYSTEMS / DEVELOPMENT",
    "assignments.facility": "FACILITY",
    "assignments.sector": "SECTOR",
    "assignments.clearance": "CLEARANCE",
    "assignments.localOperations": "LOCAL OPERATIONS",
    "assignments.arrive": "ARRIVE AT FACILITY",
    "assignments.open": "OPEN",
    "assignments.qualification.cardTitle": "FIRST OPERATOR QUALIFICATION SHIFT",
    "assignments.qualification.title": "FIRST OPERATOR QUALIFICATION SHIFT",
    "assignments.qualification.documentTitle": "FIRST OPERATOR QUALIFICATION\nSHIFT",
    "assignments.qualification.summary": "Your application for a permanent operator position at Terragen Systems has been approved.\n\nYou have been assigned your first operator qualification shift.\n\nReport to the assigned facility and complete the access procedure. Operational instructions will be provided after registration on site.",
    "assignments.reliability.title": "INSTRUMENT RELIABILITY CHECK",
    "assignments.reliability.summary": "Report to the assigned facility and complete an operating shift while identifying unreliable instruments and control indications.\n\nOperational notes will be provided after registration on site.",
    "assignments.cost.title": "COST OF RUNNING TRIAL",
    "assignments.cost.summary": "Complete the assigned operating trial while balancing required grid output against unstable low-cost fuel blends.\n\nOperational notes will be provided after registration on site.",
    "assignments.freeplay.title": "FREE SHIFT",
    "assignments.freeplay.documentTitle": "PUBLIC BUILD / FREE SHIFT",
    "assignments.freeplay.summary": "The next scheduled shifts are still in development.\n\nA ten-minute free shift is available in the public build, with a variable load schedule and randomized equipment incidents.",
    "assignments.freeplay.date": "PUBLIC BUILD / FREEPLAY",
    "levelGroups.operatorQualification": "OPERATOR QUALIFICATION",
    "levelGroups.facilityAccess": "FACILITY ACCESS",
    "levelGroups.additionalTests": "ADDITIONAL TESTS",
    "levelGroups.additionalModes": "ADDITIONAL MODES",
    "levels.intro.title": "FIRST INTRO SHIFT",
    "levels.intro.description": "First supervised fusion operation",
    "levels.coordination.title": "SHIFT COORDINATION",
    "levels.coordination.description": "Same console, clock-start shift",
    "levels.exploring.title": "EXPLORING AROUND",
    "levels.exploring.description": "The tutorial shift in the service corridor",
    "levels.unexpected.title": "UNEXPECTED STUFF",
    "levels.unexpected.description": "Instrument faults route",
    "levels.fuel.title": "COST OF RUNNING",
    "levels.fuel.description": "Fuel mix economy route",
    "levels.powerBus.title": "POWER BUS TRAINING",
    "levels.powerBus.description": "Switchgear and routing",
    "levels.longerShifts.title": "LONGER SHIFTS",
    "levels.longerShifts.description": "Ten minutes and operator effects",
    "levels.brokenLamp.title": "BROKEN LAMP",
    "levels.brokenLamp.description": "Unreliable warning indicator",
    "levels.lowFuel.title": "LOW FUEL",
    "levels.lowFuel.description": "Low reserve economy test",
    "levels.lowHeatSink.title": "LOW HEAT SINK",
    "levels.lowHeatSink.description": "Reduced thermal margin",
    "levels.maximumLoad.title": "MAX LOAD",
    "levels.maximumLoad.description": "Work near the red zone",
    "levels.freeplay.title": "FREEPLAY",
    "levels.freeplay.description": "Same console, loose targets",
    "levels.competitive.title": "COMPETITIVE",
    "levels.competitive.description": "Score route placeholder",
    "profile.dossier": "OPERATOR DOSSIER",
    "profile.status": "STATUS",
    "profile.provisional": "PROVISIONAL SHIFT OPERATOR",
    "profile.placeholder": "Performance history, route unlocks, incident tags, and operator notes will live here.",
    "pause.title": "PAUSED",
    "pause.shift": "SHIFT",
    "pause.shiftStatus": "SHIFT STATUS",
    "pause.assignment": "CURRENT ASSIGNMENT",
    "pause.elapsed": "ELAPSED",
    "actions.restartShift": "RESTART SHIFT",
    "settings.title": "SETTINGS",
    "settings.graphics": "GRAPHICS",
    "settings.controls": "CONTROLS",
    "settings.audio": "AUDIO",
    "settings.game": "GAME",
    "settings.graphicsHint": "DISPLAY AND PERFORMANCE",
    "settings.controlsHint": "VIEW AND INPUT",
    "settings.audioHint": "SOUND OUTPUT",
    "settings.gameHint": "SYSTEM AND SETUP",
    "settings.qualityHint": "OVERALL GRAPHICS QUALITY",
    "settings.renderScaleHint": "RENDERING SCALE",
    "settings.gammaHint": "IMAGE BRIGHTNESS",
    "settings.fpsHint": "AVERAGE FPS",
    "settings.resHint": "RENDER RESOLUTION",
    "settings.aaHint": "EDGE SMOOTHING",
    "settings.masterVolume": "MASTER VOLUME",
    "settings.musicVolume": "MUSIC",
    "settings.ambienceVolume": "AMBIENCE",
    "settings.interactionVolume": "INTERACTIONS",
    "settings.machineryVolume": "MACHINERY",
    "settings.speechVolume": "SPEECH",
    "settings.alarmsVolume": "ALARMS",
    "settings.playerVolume": "FOOTSTEPS",
    "settings.uiVolume": "INTERFACE",
    "settings.apply": "APPLY",
    "settings.fov": "FOV",
    "settings.uiScale": "UI SCALE",
    "settings.sensitivity": "CONTROL SENSITIVITY",
    "settings.shadows": "SHADOWS",
    "settings.gtao": "AO",
    "settings.wizard": "SETUP WIZARD",
    "settings.resetObjects": "RESET OBJECTS",
    "settings.resetProgress": "RESET PROGRESS",
    "controls.fuelInjection": "FUEL INJECTION",
    "controls.magneticField": "MAGNETIC FIELD",
    "controls.coolantFlow": "COOLANT FLOW",
    "controls.indicatorTest": "INDICATOR TEST",
    "controls.startCore": "START CORE",
    "controls.pulse": "PULSE",
    "controls.vent": "EMERGENCY VENT / PURGE",
    "controls.roomLights": "ROOM LIGHTS",
    "controls.viewportShutter": "VIEWPORT SHUTTER",
    "controls.bulkhead": "BULKHEAD HANDLE",
    "controls.bulkheadLock": "BULKHEAD LOCK",
    "controls.holdBulkhead": "HOLD TO OPEN BULKHEAD",
    "controls.on": "ON",
    "controls.off": "OFF",
    "hints.move": "Press {keys} to move.",
    "hints.jump": "Press {key} to say apple.",
    "hints.lean": "Hold {button} to lean toward the panel.",
    "hints.wheel": "Use {wheel} to tune the highlighted control.",
    "hints.exploringMove": "Use {keys} to move.",
    "hints.exploringLook": "Move the {button} to look around.",
    "hints.exploringDoorLook": "Look at the door handle.",
    "hints.exploringDoor": "Hold {button} to open the door.",
    "hints.exploringBrief": "Access the service terminal.",
    "hints.exploringBriefHold": "Hold {button} to take the brief.",
    "hints.exploringBriefInventory": "Hold {key}, select the brief with {wheel}, then release.",
    "hints.flashlightInventory": "Hold {key}, select the flashlight with {wheel}, then release.",
    "hints.flashlightActivate": "Press {key} to activate the flashlight.",
    "hints.exploringLean": "Hold {button} to lean toward the panel.",
    "hints.exploringWheel": "Use {wheel} to adjust the control.",
    "hints.exploringButton": "Press {button} to activate.",
    "subtitles.tutorial-control-booth": "I think he meant the Control Booth.",
    "subtitles.tutorial-apple": "I don't think that was it.",
    "subtitles.tutorial-start-core": "I think I need to start it.",
    "subtitles.field-weak": "Easy. Too early.",
    "subtitles.first-quench": "Damn. Drowned it. Back off the coolant... give it fuel...",
    "subtitles.pulse-ready": "Come on. Take the spark.",
    "subtitles.restart-success": "There you are.",
    "subtitles.first-redline": "Nope. That's way too hot.",
    "subtitles.high-load": "Hold together. Just a little longer.",
    "subtitles.door-live-core": "Yeah, no. Can't leave it burning.",
    "subtitles.door-interlocked": "Of course. Interlocked until shutdown.",
    "subtitles.door-shift-incomplete": "Finish the shift first.",
    "subtitles.shift-complete": "Done. Time to leave.",
    "subtitles.core-destroyed": "That's gone. I need out. Now.",
    "subtitles.fail-safe": "Fail-safe caught it. Time to go.",
    "subtitles.shift-exit": "I should head back to the entrance.",
    "subtitles.shift-exit-corridor": "The exit bulkhead is back this way.",
    "subtitles.startup-command-fault": "Shouldn't have done that.",
  },
  ru: {
    "loading.coreBoot": "ЗАПУСК ЯДРА",
    "loading.initializing": "ИНИЦИАЛИЗАЦИЯ ПУЛЬТА ОПЕРАТОРА",
    "loading.coreOnline": "ИНТЕРФЕЙС ЯДРА ГОТОВ",
    "loading.firstShift": "ВАША ПЕРВАЯ СМЕНА",
    "loading.shiftLoad": "ЗАГРУЗКА СМЕНЫ",
    "loading.preparing": "ПОДГОТОВКА ПУЛЬТА ОПЕРАТОРА",
    "loading.loadingShift": "ЗАГРУЗКА СМЕНЫ",
    "loading.returning": "ВОЗВРАТ К ПУЛЬТУ ОПЕРАТОРА",
    "loading.restartingShift": "ПЕРЕЗАПУСК СМЕНЫ",
    "loading.resettingCore": "СБРОС СОСТОЯНИЯ ЯДРА",
    "loading.shift": "СМЕНА",
    "loading.textures": "Загрузка текстур",
    "briefing.prompt": "ENTER — СПРЯТАТЬ · Q — ВЫБРОСИТЬ",
    "results.report": "ОТЧЁТ О СМЕНЕ",
    "results.profile": "ПРОФИЛЬ ОПЕРАТОРА",
    "results.awaiting": "Ожидание данных смены.",
    "results.outcome.complete": "ЗАВЕРШЕНО",
    "results.outcome.failed": "ПРОВАЛ",
    "results.title.qualification.complete": "КВАЛИФИКАЦИЯ ПРОЙДЕНА",
    "results.title.qualification.failed": "КВАЛИФИКАЦИЯ НЕ ПРОЙДЕНА",
    "results.summary.qualification.complete": "Все фазы нагрузки выполнены. Параметры эксплуатации находятся в пределах допуска.",
    "results.summary.qualification.failed": "Требования квалификации не выполнены. Перед повтором смены изучите зарегистрированные показатели.",
    "results.comment.qualification.complete": "Параметры эксплуатации находятся в пределах допуска. Оператор допущен к последующим назначенным сменам.",
    "results.comment.qualification.failed": "Требования квалификации не выполнены.",
    "results.title.reliability.complete": "ПРОВЕРКА ПРИБОРОВ ПРОЙДЕНА",
    "results.title.reliability.failed": "ПРОВЕРКА ПРИБОРОВ НЕ ПРОЙДЕНА",
    "results.summary.reliability.complete": "Рабочая смена завершена в условиях ненадёжных показаний приборов и органов управления.",
    "results.summary.reliability.failed": "Требования проверки надёжности не выполнены. Перед повтором смены изучите зарегистрированные события.",
    "results.comment.reliability.complete": "Оператор сохранил безопасный режим, сопоставляя ненадёжные показания. Проверка надёжности приборов завершена.",
    "results.comment.reliability.failed": "Проверка надёжности приборов не завершена.",
    "results.title.cost.complete": "ИСПЫТАНИЕ ЗАТРАТ ПРОЙДЕНО",
    "results.title.cost.failed": "ИСПЫТАНИЕ ЗАТРАТ НЕ ПРОЙДЕНО",
    "results.summary.cost.complete": "Требуемая выдача в сеть обеспечена в допустимых пределах испытания дешёвой топливной смеси.",
    "results.summary.cost.failed": "Требования к выдаче и стоимости эксплуатации не выполнены. Перед повтором испытания изучите зарегистрированные показатели.",
    "results.comment.cost.complete": "Назначенная топливная смесь признана пригодной к эксплуатации. Выдача мощности и состояние реактора приняты.",
    "results.comment.cost.failed": "Требования эксплуатационного испытания не выполнены.",
    "results.title.freeplay.complete": "СВОБОДНАЯ СМЕНА ЗАВЕРШЕНА",
    "results.title.freeplay.failed": "СВОБОДНАЯ СМЕНА ПРЕРВАНА",
    "results.summary.freeplay.complete": "Десятиминутная смена публичной версии с переменным графиком нагрузки завершена.",
    "results.summary.freeplay.failed": "Свободная смена завершилась до выполнения всех рабочих требований.",
    "results.comment.freeplay.complete": "Запись свободной смены принята. Последующие плановые смены находятся в разработке.",
    "results.comment.freeplay.failed": "Запись свободной смены закрыта без завершения.",
    "results.keyMetrics": "КЛЮЧЕВЫЕ ПОКАЗАТЕЛИ",
    "results.serviceComment": "СЛУЖЕБНЫЙ КОММЕНТАРИЙ",
    "results.shift.exploring-around": "SITE-12 / КВАЛИФИКАЦИОННАЯ СМЕНА",
    "results.shift.intro-shift": "SITE-12 / КВАЛИФИКАЦИОННАЯ СМЕНА",
    "results.shift.unexpected-stuff": "SITE-12 / ПРОВЕРКА НАДЁЖНОСТИ ПРИБОРОВ",
    "results.shift.fuel-problems": "SITE-12 / ИСПЫТАНИЕ ЗАТРАТ",
    "results.shift.freeplay": "SITE-12 / СВОБОДНАЯ СМЕНА",
    "results.schedule.exploring-around": "01.05.2036 / 06:42–06:45",
    "results.schedule.intro-shift": "01.05.2036 / 06:42–06:45",
    "results.schedule.unexpected-stuff": "02.05.2036 / 06:00–06:03",
    "results.schedule.freeplay": "ПУБЛИЧНАЯ ВЕРСИЯ / СМЕНА 10:00",
    "results.schedule.fuel-problems": "07.05.2037 / 21:40–21:43",
    "results.status.acceptable": "ПРИЕМЛЕМАЯ",
    "results.status.reviewRequired": "ТРЕБУЕТ ПРОВЕРКИ",
    "results.failure.gridCompliance": "Соответствие запросу сети осталось ниже квалификационного порога.",
    "results.failure.operatingEfficiency": "Рабочий баланс реактора остался ниже требуемой эффективности.",
    "results.failure.peakCoreStress": "Пиковый стресс ядра превысил допустимый предел квалификации.",
    "results.failure.criticalTemperature": "Критическая температура плазмы сохранялась дольше допустимого.",
    "results.failure.coreStall": "Состояние срыва горения сохранялось дольше допустимого.",
    "results.failure.instability": "Нестабильность удержания сохранялась дольше допустимого.",
    "results.failure.sustainedDemandDeviation": "Сильное отклонение от запроса сети сохранялось слишком долго.",
    "results.failure.phaseTracking": "Недостаточное число фаз нагрузки выполнено в пределах допуска.",
    "results.failure.qualityFailure": "Качество выдаваемой мощности осталось ниже требований смены.",
    "results.failure.coreDestroyed": "Стресс ядра превысил конструкционный предел эксплуатации.",
    "results.failure.safeShutdown": "Реакция была потеряна до завершения назначенной смены.",
    "results.failure.unknown": "Смена завершена без выполнения квалификационных требований.",
    "results.stats.shiftTime": "ВРЕМЯ СМЕНЫ",
    "results.stats.avgEfficiency": "СРЕДНЯЯ ЭФФЕКТИВНОСТЬ",
    "results.stats.avgOutput": "СРЕДНЯЯ МОЩНОСТЬ",
    "results.stats.maxOutput": "ПИКОВАЯ МОЩНОСТЬ",
    "results.stats.avgDemandError": "ОШИБКА ЗАПРОСА СЕТИ",
    "results.stats.gridCompliance": "СООТВЕТСТВИЕ СПРОСУ",
    "results.stats.phasesPassed": "ПРОЙДЕНО ФАЗ",
    "results.stats.stability": "СТАБИЛЬНОСТЬ",
    "results.stats.warningEvents": "ПРЕДУПРЕЖДЕНИЯ",
    "results.stats.criticalEvents": "КРИТИЧЕСКИЕ СОБЫТИЯ",
    "results.stats.emergencyInterventions": "АВАРИЙНЫЕ ВМЕШАТЕЛЬСТВА",
    "results.stats.maxTemp": "МАКС. ТЕМПЕРАТУРА",
    "results.stats.maxCoreStress": "МАКС. СТРЕСС ЯДРА",
    "results.stats.maxHeatSoak": "МАКС. ТЕПЛОВОЙ ЗАПАС",
    "results.stats.criticalTemp": "КРИТИЧЕСКАЯ ТЕМП.",
    "results.stats.outputSurge": "СКАЧКИ МОЩНОСТИ",
    "results.stats.overDemand": "ПЕРЕВЫДАЧА",
    "results.stats.underDemand": "НЕДОВЫДАЧА",
    "results.stats.coreStall": "СРЫВ ГОРЕНИЯ",
    "results.stats.ventHeld": "СБРОС УДЕРЖИВАЛСЯ",
    "results.stats.ventPulses": "ИМПУЛЬСЫ СБРОСА",
    "results.stats.pulseUses": "ИМПУЛЬСЫ ЗАПУСКА",
    "results.stats.avgTemp": "СРЕДНЯЯ ТЕМП.",
    "results.stats.controlMotion": "ДВИЖЕНИЕ КОНТРОЛОВ",
    "results.profile.containmentPostmortem.title": "ТИП ОПЕРАТОРА: ПОСМЕРТНЫЙ ОТЧЁТ КОНТЕЙНМЕНТА",
    "results.profile.containmentPostmortem.summary": "Вы нашли участок рабочего диапазона, после которого отчёты пишутся капсом.",
    "results.profile.nervousPurgeTech.title": "ТИП ОПЕРАТОРА: НЕРВНЫЙ ТЕХНИК СБРОСА",
    "results.profile.nervousPurgeTech.summary": "Короткие сбросы решили несколько проблем и создали несколько новых записей в журнале.",
    "results.profile.fieldPhysicist.title": "ТИП ОПЕРАТОРА: ФИЗИК ПОЛЯ",
    "results.profile.fieldPhysicist.summary": "Спокойные руки, хорошая связь, приемлемая дисциплина сети. Подозрительно компетентно.",
    "results.profile.highLoadSpecialist.title": "ТИП ОПЕРАТОРА: СПЕЦИАЛИСТ ВЫСОКОЙ НАГРУЗКИ",
    "results.profile.highLoadSpecialist.summary": "Вы держали горение горячим намеренно и почти убедили оборудование, что так и было задумано.",
    "results.profile.redlinePhilosopher.title": "ТИП ОПЕРАТОРА: ФИЛОСОФ КРАСНОЙ ЗОНЫ",
    "results.profile.redlinePhilosopher.summary": "Вы спорили с тепловым запасом философски. У панели были аргументы.",
    "results.profile.busSurgeConductor.title": "ТИП ОПЕРАТОРА: ДИРИЖЁР СКАЧКОВ ШИНЫ",
    "results.profile.busSurgeConductor.summary": "Сеть получала мощность выразительными волнами. Некоторые даже были полезны.",
    "results.profile.gridOverfeeder.title": "ТИП ОПЕРАТОРА: ПЕРЕКОРМ СЕТИ",
    "results.profile.gridOverfeeder.summary": "Запрос сети был целью. Вы восприняли его как нижнюю границу.",
    "results.profile.fuelIntoNoise.title": "ТИП ОПЕРАТОРА: ТОПЛИВО В ШУМ",
    "results.profile.fuelIntoNoise.summary": "Много топлива стало теплом, тревогами и опытом, прежде чем стать мощностью.",
    "results.profile.magneticAccountant.title": "ТИП ОПЕРАТОРА: МАГНИТНЫЙ БУХГАЛТЕР",
    "results.profile.magneticAccountant.summary": "Контейнмент был идеально оформлен. Полезная мощность впечатлилась меньше.",
    "results.profile.heatSinkGambler.title": "ТИП ОПЕРАТОРА: ИГРОК НА ТЕПЛООТВОДЕ",
    "results.profile.heatSinkGambler.summary": "Вы доверяли тепловой массе дольше, чем советует инструкция, но свет остался включён.",
    "results.profile.coolantIntern.title": "ТИП ОПЕРАТОРА: СТАЖЁР ОХЛАДИТЕЛЯ",
    "results.profile.coolantIntern.summary": "Плазма большую часть смены пыталась понять, почему её охлаждают вместо эксплуатации.",
    "results.profile.underpoweredOptimist.title": "ТИП ОПЕРАТОРА: НЕДОМОЩНЫЙ ОПТИМИСТ",
    "results.profile.underpoweredOptimist.summary": "Сеть просила больше. Вы сохраняли изящную дистанцию от её просьб.",
    "results.profile.whyIsThisLampBlinking.title": "ТИП ОПЕРАТОРА: ПОЧЕМУ МИГАЕТ ЛАМПА",
    "results.profile.whyIsThisLampBlinking.summary": "Вы внесли много коррекций. Некоторые даже относились к проблеме.",
    "results.profile.controlRoomStatue.title": "ТИП ОПЕРАТОРА: СТАТУЯ В ОПЕРАТОРСКОЙ",
    "results.profile.controlRoomStatue.summary": "Панель меняла фазы. Вы уважали её независимость.",
    "results.profile.edgeWalker.title": "ТИП ОПЕРАТОРА: ХОДЯЩИЙ ПО КРАЮ",
    "results.profile.edgeWalker.summary": "Вы часто заходили в красную зону, но уходили до того, как она становилась постоянной.",
    "results.profile.unscheduledExperiment.title": "ТИП ОПЕРАТОРА: НЕЗАПЛАНИРОВАННЫЙ ЭКСПЕРИМЕНТ",
    "results.profile.unscheduledExperiment.summary": "Смена закончилась полезными данными. Техслужба может подобрать другие слова.",
    "results.profile.shiftOperator.title": "ТИП ОПЕРАТОРА: ОПЕРАТОР СМЕНЫ",
    "results.profile.shiftOperator.summary": "Вы держали ядро в работе, шли на компромиссы и оставили достаточно машины следующему.",
    "results.profile.peakOutputTourist.title": "ТИП ОПЕРАТОРА: ТУРИСТ ПИКОВОЙ МОЩНОСТИ",
    "results.profile.peakOutputTourist.summary": "Вы сходили посмотреть на максимум мощности и вернули большую часть оборудования.",
    "results.profile.reactionPoet.title": "ТИП ОПЕРАТОРА: ПОЭТ РЕАКЦИИ",
    "results.profile.reactionPoet.summary": "Числа сложились в эмоциональную арку. Сеть попросила меньше метафор.",
    "results.profile.panelApprentice.title": "ТИП ОПЕРАТОРА: УЧЕНИК ПАНЕЛИ",
    "results.profile.panelApprentice.summary": "Вы узнали, какие лампы важны, а какие просто осуждают.",
    "menu.subtitle": "ПУЛЬТ УПРАВЛЕНИЯ ТЕРМОЯДЕРНЫМ ЯДРОМ",
    "actions.startWork": "НАЧАТЬ РАБОТУ",
    "actions.credits": "ТИТРЫ",
    "actions.newShift": "НАЧАТЬ НОВУЮ СМЕНУ",
    "actions.levelSelect": "ВЫБОР СМЕНЫ",
    "actions.mainMenu": "ГЛАВНОЕ МЕНЮ",
    "actions.play": "ИГРАТЬ",
    "actions.profile": "ПРОФИЛЬ",
    "actions.settings": "НАСТРОЙКИ",
    "actions.back": "НАЗАД",
    "actions.resume": "ПРОДОЛЖИТЬ",
    "actions.menu": "МЕНЮ",
    "actions.restart": "ПЕРЕЗАПУСТИТЬ",
    "actions.continue": "ПРОДОЛЖИТЬ",
    "actions.repeatShift": "ПОВТОРИТЬ СМЕНУ",
    "credits.title": "ТИТРЫ",
    "credits.development": "РАБОЧАЯ ВЕРСИЯ",
    "credits.placeholder": "Полный список участников будет добавлен в процессе разработки.",
    "levels.route": "МАРШРУТ СМЕН",
    "assignments.heading": "НАЗНАЧЕННЫЕ СМЕНЫ",
    "assignments.applicationApproved": "ЗАЯВКА ОДОБРЕНА",
    "assignments.assigned": "НАЗНАЧЕНО",
    "assignments.notAssigned": "- НЕ НАЗНАЧЕНО -",
    "assignments.nothingSelected": "- НИЧЕГО НЕ ВЫБРАНО -",
    "assignments.startShift": "НАЧАТЬ СМЕНУ",
    "assignments.approved": "ОДОБРЕНО",
    "assignments.noMore": "НАЗНАЧЕНИЙ БОЛЬШЕ НЕТ",
    "assignments.archiveEmpty": "АРХИВ ПУСТ",
    "assignments.completed": "ЗАВЕРШЕНО",
    "assignments.operationsSubject": "TERRAGEN SYSTEMS / OPERATIONS",
    "assignments.developmentSubject": "TERRAGEN SYSTEMS / РАЗРАБОТКА",
    "assignments.facility": "МЕСТО НАЗНАЧЕНИЯ",
    "assignments.sector": "СЕКТОР",
    "assignments.clearance": "ЯВКА",
    "assignments.localOperations": "LOCAL OPERATIONS",
    "assignments.arrive": "ПРИБЫТЬ НА ОБЪЕКТ",
    "assignments.open": "ОТКРЫТЬ",
    "assignments.qualification.cardTitle": "ПЕРВАЯ КВАЛИФИКАЦИОННАЯ СМЕНА ОПЕРАТОРА",
    "assignments.qualification.title": "ПЕРВАЯ КВАЛИФИКАЦИОННАЯ СМЕНА ОПЕРАТОРА",
    "assignments.qualification.documentTitle": "ПЕРВАЯ КВАЛИФИКАЦИОННАЯ\nСМЕНА ОПЕРАТОРА",
    "assignments.qualification.summary": "Ваша заявка на должность постоянного оператора Terragen Systems была одобрена.\n\nВам назначена первая квалификационная смена оператора.\n\nПрибудьте на объект и пройдите процедуру допуска. Рабочие инструкции будут предоставлены системой после регистрации на объекте.",
    "assignments.reliability.title": "ПРОВЕРКА НАДЁЖНОСТИ ПРИБОРОВ",
    "assignments.reliability.summary": "Прибудьте на назначенный объект и проведите смену, выявляя ненадёжные приборы и ошибочные показания органов управления.\n\nРабочие инструкции будут предоставлены после регистрации на объекте.",
    "assignments.cost.title": "ИСПЫТАНИЕ СТОИМОСТИ ЭКСПЛУАТАЦИИ",
    "assignments.cost.summary": "Проведите назначенную смену, балансируя требуемую мощность для сети и нестабильные дешёвые топливные смеси.\n\nРабочие инструкции будут предоставлены после регистрации на объекте.",
    "assignments.freeplay.title": "СВОБОДНАЯ СМЕНА",
    "assignments.freeplay.documentTitle": "ПУБЛИЧНАЯ ВЕРСИЯ / СВОБОДНАЯ СМЕНА",
    "assignments.freeplay.summary": "Последующие плановые смены пока находятся в разработке.\n\nВ публичной версии доступна десятиминутная свободная смена со случайным графиком нагрузки и случайными происшествиями.",
    "assignments.freeplay.date": "ПУБЛИЧНАЯ ВЕРСИЯ / FREEPLAY",
    "levelGroups.operatorQualification": "КВАЛИФИКАЦИЯ ОПЕРАТОРА",
    "levelGroups.facilityAccess": "ДОСТУП К ОБЪЕКТУ",
    "levelGroups.additionalTests": "ДОП. ТЕСТЫ",
    "levelGroups.additionalModes": "ДОП. РЕЖИМЫ",
    "levels.intro.title": "ПЕРВАЯ ВВОДНАЯ СМЕНА",
    "levels.intro.description": "Первая контролируемая работа с ядром",
    "levels.coordination.title": "КООРДИНАЦИЯ СМЕНЫ",
    "levels.coordination.description": "Та же операторская, запуск смены по часам",
    "levels.exploring.title": "ИССЛЕДОВАНИЕ",
    "levels.exploring.description": "Учебная смена в сервисном коридоре",
    "levels.unexpected.title": "НЕОЖИДАННОСТИ",
    "levels.unexpected.description": "Маршрут неисправностей приборов",
    "levels.fuel.title": "СТОИМОСТЬ СМЕНЫ",
    "levels.fuel.description": "Экономия на топливной смеси",
    "levels.powerBus.title": "ОБУЧЕНИЕ ЩИТОВОЙ",
    "levels.powerBus.description": "Шина питания и маршрутизация",
    "levels.longerShifts.title": "ДЛИННЫЕ СМЕНЫ",
    "levels.longerShifts.description": "10 минут и эффекты оператора",
    "levels.brokenLamp.title": "СЛОМАННАЯ ЛАМПА",
    "levels.brokenLamp.description": "Ненадёжный предупреждающий индикатор",
    "levels.lowFuel.title": "МАЛО ТОПЛИВА",
    "levels.lowFuel.description": "Экономия при низком резерве",
    "levels.lowHeatSink.title": "МАЛО HEAT SINK",
    "levels.lowHeatSink.description": "Меньше тепловой запас",
    "levels.maximumLoad.title": "МАКС. НАГРУЗКА",
    "levels.maximumLoad.description": "Работа у красной зоны",
    "levels.freeplay.title": "СВОБОДНЫЙ РЕЖИМ",
    "levels.freeplay.description": "Тот же пульт, свободные цели",
    "levels.competitive.title": "СОРЕВНОВАНИЕ",
    "levels.competitive.description": "Рейтинговый маршрут",
    "profile.dossier": "ДОСЬЕ ОПЕРАТОРА",
    "profile.status": "СТАТУС",
    "profile.provisional": "СТАЖЁР-ОПЕРАТОР",
    "profile.placeholder": "Здесь появятся история смен, открытые маршруты, инциденты и заметки оператора.",
    "pause.title": "ПАУЗА",
    "pause.shift": "СМЕНА",
    "pause.shiftStatus": "СТАТУС СМЕНЫ",
    "pause.assignment": "ТЕКУЩЕЕ ЗАДАНИЕ",
    "pause.elapsed": "ПРОШЛО",
    "actions.restartShift": "ПЕРЕЗАПУСТИТЬ СМЕНУ",
    "settings.title": "НАСТРОЙКИ",
    "settings.graphics": "ГРАФИКА",
    "settings.controls": "УПРАВЛЕНИЕ",
    "settings.audio": "АУДИО",
    "settings.game": "ИГРА",
    "settings.graphicsHint": "ПАРАМЕТРЫ ИЗОБРАЖЕНИЯ И ПРОИЗВОДИТЕЛЬНОСТИ",
    "settings.controlsHint": "ОБЗОР И УПРАВЛЕНИЕ",
    "settings.audioHint": "ЗВУК",
    "settings.gameHint": "СИСТЕМА И НАСТРОЙКА",
    "settings.qualityHint": "ОБЩЕЕ КАЧЕСТВО ГРАФИКИ",
    "settings.renderScaleHint": "МАСШТАБ РЕНДЕРИНГА",
    "settings.gammaHint": "ЯРКОСТЬ ИЗОБРАЖЕНИЯ",
    "settings.fpsHint": "СРЕДНИЙ FPS",
    "settings.resHint": "РАЗРЕШЕНИЕ РЕНДЕРА",
    "settings.aaHint": "СГЛАЖИВАНИЕ",
    "settings.masterVolume": "ОБЩАЯ ГРОМКОСТЬ",
    "settings.musicVolume": "МУЗЫКА",
    "settings.ambienceVolume": "ОКРУЖЕНИЕ",
    "settings.interactionVolume": "ВЗАИМОДЕЙСТВИЯ",
    "settings.machineryVolume": "ОБОРУДОВАНИЕ",
    "settings.speechVolume": "РЕЧЬ",
    "settings.alarmsVolume": "СИГНАЛЫ ТРЕВОГИ",
    "settings.playerVolume": "ШАГИ",
    "settings.uiVolume": "ИНТЕРФЕЙС",
    "settings.apply": "ПРИМЕНИТЬ",
    "settings.fov": "УГОЛ ОБЗОРА",
    "settings.uiScale": "МАСШТАБ ИНТЕРФЕЙСА",
    "settings.sensitivity": "ЧУВСТВИТЕЛЬНОСТЬ УПРАВЛЕНИЯ",
    "settings.shadows": "ТЕНИ",
    "settings.gtao": "AO",
    "settings.wizard": "МАСТЕР НАСТРОЙКИ",
    "settings.resetObjects": "СБРОСИТЬ ОБЪЕКТЫ",
    "settings.resetProgress": "СБРОСИТЬ ПРОГРЕСС",
    "controls.fuelInjection": "ПОДАЧА ТОПЛИВА",
    "controls.magneticField": "МАГНИТНОЕ ПОЛЕ",
    "controls.coolantFlow": "ПОТОК ОХЛАДИТЕЛЯ",
    "controls.indicatorTest": "ПРОВЕРКА ИНДИКАТОРОВ",
    "controls.startCore": "ЗАПУСК ЯДРА",
    "controls.pulse": "ИМПУЛЬС",
    "controls.vent": "АВАРИЙНЫЙ СБРОС",
    "controls.roomLights": "ОСВЕЩЕНИЕ",
    "controls.viewportShutter": "ЗАСЛОНКА СМОТРОВОГО ОКНА",
    "controls.bulkhead": "РУКОЯТКА ШЛЮЗА",
    "controls.bulkheadLock": "ЗАМОК ШЛЮЗА",
    "controls.holdBulkhead": "УДЕРЖИВАЙТЕ, ЧТОБЫ ОТКРЫТЬ ШЛЮЗ",
    "controls.on": "ВКЛ",
    "controls.off": "ВЫКЛ",
    "hints.move": "Нажмите {keys}, чтобы двигаться.",
    "hints.jump": "Нажмите {key}, чтобы сказать «яблоко».",
    "hints.lean": "Удерживайте {button}, чтобы наклониться к панели.",
    "hints.wheel": "Крутите {wheel}, чтобы регулировать выбранный контрол.",
    "hints.exploringMove": "Используйте {keys}, чтобы двигаться.",
    "hints.exploringLook": "Двигайте {button}, чтобы осматриваться.",
    "hints.exploringDoorLook": "Посмотрите на ручку двери.",
    "hints.exploringDoor": "Зажмите {button}, чтобы открыть дверь.",
    "hints.exploringBrief": "Откройте служебный терминал.",
    "hints.exploringBriefHold": "Зажмите {button}, чтобы взять бриф.",
    "hints.exploringBriefInventory": "Зажмите {key}, выберите бриф через {wheel} и отпустите.",
    "hints.flashlightInventory": "Зажмите {key}, выберите фонарик через {wheel} и отпустите.",
    "hints.flashlightActivate": "Нажмите {key}, чтобы активировать фонарик.",
    "hints.exploringLean": "Зажмите {button}, чтобы наклониться к панели.",
    "hints.exploringWheel": "Используйте {wheel}, чтобы регулировать контрол.",
    "hints.exploringButton": "Нажмите {button}, чтобы активировать.",
    "subtitles.tutorial-control-booth": "Думаю, он имел в виду Control Booth.",
    "subtitles.tutorial-apple": "Кажется, не то.",
    "subtitles.tutorial-start-core": "Думаю, его надо запустить.",
    "subtitles.field-weak": "Спокойно. Ещё рано.",
    "subtitles.first-quench": "Чёрт. Залил плазму. Меньше охладителя... добавить топлива...",
    "subtitles.pulse-ready": "Давай. Лови искру.",
    "subtitles.restart-success": "Вот так.",
    "subtitles.first-redline": "Нет. Слишком горячо.",
    "subtitles.high-load": "Держись. Ещё немного.",
    "subtitles.door-live-core": "Нет уж. Нельзя уходить, пока ядро горит.",
    "subtitles.door-interlocked": "Ну конечно. Заблокировано до остановки.",
    "subtitles.door-shift-incomplete": "Сначала надо завершить смену.",
    "subtitles.shift-complete": "Дело сделано, пора уходить.",
    "subtitles.core-destroyed": "Ему конец. Нужно выбираться. Сейчас.",
    "subtitles.fail-safe": "Защита сработала. Пора уходить.",
    "subtitles.shift-exit": "Надо возвращаться ко входу.",
    "subtitles.shift-exit-corridor": "Выходной шлюз в этой стороне.",
    "subtitles.startup-command-fault": "Не стоило этого делать.",
  },
};

export function normalizeLanguage(language) {
  return language === "ru" ? "ru" : "en";
}

export function translate(key, language = document.documentElement.lang) {
  const normalized = normalizeLanguage(language);
  return STRINGS[normalized][key] ?? STRINGS.en[key] ?? key;
}

export function translateRequired(key, language = document.documentElement.lang) {
  const normalized = normalizeLanguage(language);
  const localized = STRINGS[normalized][key];
  const english = STRINGS.en[key];
  if (localized && english) return localized;
  console.error(`[Localization] Missing required EN/RU translation: ${key}`);
  return `[MISSING TRANSLATION: ${key}]`;
}

export function applyLocalization(language, root = document) {
  const normalized = normalizeLanguage(language);
  document.documentElement.lang = normalized;
  root.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = translate(element.dataset.i18n, normalized);
  });
  return normalized;
}

const CONTROL_LABEL_KEYS = {
  "FUEL INJECTION": "controls.fuelInjection",
  "MAGNETIC FIELD": "controls.magneticField",
  "COOLANT FLOW": "controls.coolantFlow",
  "INDICATOR TEST": "controls.indicatorTest",
  "START CORE": "controls.startCore",
  PULSE: "controls.pulse",
  "EMERGENCY VENT / PURGE": "controls.vent",
  "ROOM LIGHTS": "controls.roomLights",
  "VIEWPORT SHUTTER": "controls.viewportShutter",
  "BULKHEAD HANDLE": "controls.bulkhead",
  "BULKHEAD LOCK": "controls.bulkheadLock",
  "HOLD TO OPEN BULKHEAD": "controls.holdBulkhead",
};

export function translateControlLabel(label, language = document.documentElement.lang) {
  const key = CONTROL_LABEL_KEYS[label];
  return key ? translate(key, language) : label;
}
