const DEFAULT_FACILITY_ACTIVITY_CONFIG = {
  enabled: true,
  checkIntervalRangeSeconds: [8, 15],
  chance: 0.32,
  recentHistorySize: 3,
  uncannyChance: 0.04,
  emitters: {
    reactorWall: { position: { x: 3.8, y: 1.9, z: -3.7 } },
    deepServices: { position: { x: -5.8, y: 2.2, z: 5.4 } },
    pumpSide: { position: { x: 3.4, y: 1.2, z: 10.6 } },
    powerBus: { position: { x: -3.4, y: 2.1, z: 16.5 } },
    serviceShaft: { position: { x: -1.6, y: 3.3, z: 27.5 } },
  },
  sounds: [
    {
      id: "spin-down",
      file: "DistantSpinDown1",
      category: "machinery",
      weight: 1,
      minCooldown: 25,
      maxCooldown: 48,
      volume: 0.42,
      pitchVariation: 0.045,
      allowRepeat: true,
      emitterIds: ["reactorWall", "powerBus"],
      duration: 4.84,
      refDistance: 3.5,
      maxDistance: 32,
    },
    {
      id: "machinery-whistle",
      file: "DistantWhistleMachinery1",
      category: "machinery",
      weight: 0.85,
      minCooldown: 38,
      maxCooldown: 64,
      volume: 0.31,
      pitchVariation: 0.035,
      allowRepeat: true,
      emitterIds: ["powerBus", "deepServices"],
      duration: 8.11,
      refDistance: 3.5,
      maxDistance: 35,
    },
    {
      id: "metal-screech",
      file: "DistantMetalScreech1",
      category: "structural",
      weight: 0.72,
      minCooldown: 48,
      maxCooldown: 76,
      volume: 0.25,
      pitchVariation: 0.03,
      allowRepeat: true,
      emitterIds: ["serviceShaft", "deepServices"],
      duration: 12.31,
      refDistance: 4,
      maxDistance: 38,
    },
    {
      id: "huge-metal-move",
      file: "DistantHugeMetalMove1",
      category: "deep",
      weight: 0.55,
      minCooldown: 58,
      maxCooldown: 80,
      volume: 0.27,
      pitchVariation: 0.025,
      allowRepeat: true,
      emitterIds: ["deepServices", "pumpSide"],
      duration: 15.25,
      refDistance: 4.5,
      maxDistance: 42,
    },
    {
      id: "elevator-gears",
      file: "DistantElevatorGears1",
      category: "machinery",
      weight: 0.58,
      minCooldown: 55,
      maxCooldown: 80,
      volume: 0.28,
      pitchVariation: 0.025,
      allowRepeat: true,
      emitterIds: ["serviceShaft", "pumpSide"],
      duration: 16.38,
      refDistance: 4.5,
      maxDistance: 42,
    },
    {
      id: "lurking-bass",
      file: "DistantBassLurking1",
      category: "uncanny",
      weight: 1,
      minCooldown: 90,
      maxCooldown: 130,
      volume: 0.18,
      pitchVariation: 0.02,
      once: true,
      allowRepeat: false,
      emitterIds: ["deepServices", "reactorWall"],
      duration: 11.54,
      refDistance: 5,
      maxDistance: 46,
    },
  ],
  events: [
    { id: "spin-down", weight: 1, steps: [{ soundId: "spin-down" }] },
    {
      id: "pressure-release",
      weight: 0.85,
      steps: [
        { soundId: "machinery-whistle" },
        { soundId: "spin-down", delayRangeSeconds: [2, 5] },
      ],
    },
    { id: "metal-screech", weight: 0.72, steps: [{ soundId: "metal-screech" }] },
    {
      id: "elevator-transfer",
      weight: 0.58,
      steps: [
        { soundId: "elevator-gears" },
        { soundId: "huge-metal-move", delayRangeSeconds: [4, 8] },
      ],
    },
    { id: "deep-metal-move", weight: 0.55, steps: [{ soundId: "huge-metal-move" }] },
    { id: "lurking-bass", weight: 1, category: "uncanny", steps: [{ soundId: "lurking-bass" }] },
  ],
};

export function createFacilityActivityConfig() {
  return structuredClone(DEFAULT_FACILITY_ACTIVITY_CONFIG);
}
