export const SOUND_REGISTRY = {
  Ambience_EntryHall1: {
    path: "assets/sounds/ambience/AmbienceLoop_EntryHall1.ogg",
    loop: true,
    volume: 0.38,
    fadeDistance: 1.8,
  },
  Ambience_Cave1: {
    path: "assets/sounds/ambience/Ambience_Cave1.ogg",
    loop: true,
    volume: 0.36,
    fadeDistance: 1.6,
  },
  Ambience_CaveWindy1: {
    path: "assets/sounds/ambience/Ambience_CaveWindy1.ogg",
    loop: true,
    volume: 0.42,
    fadeDistance: 1.8,
  },
  Button_Light1: { path: "assets/sounds/interaction/Button_Light1.ogg", volume: 0.48 },
  Button_Light2: { path: "assets/sounds/interaction/Button_Light2.ogg", volume: 0.48 },
  Button_Light3: { path: "assets/sounds/interaction/Button_Light3.ogg", volume: 0.48 },
  ButtonMechanical1: { path: "assets/sounds/interaction/ButtonMechanical1.ogg", volume: 0.62 },
  ButtonMechanical2: { path: "assets/sounds/interaction/ButtonMechanical2.ogg", volume: 0.62 },
  ButtonMechanical3: { path: "assets/sounds/interaction/ButtonMechanical3.ogg", volume: 0.62 },
  ButtonMechanical4: { path: "assets/sounds/interaction/ButtonMechanical4.ogg", volume: 0.62 },
  BeepShortLight1: { path: "assets/sounds/interaction/BeepShortLight1.ogg", volume: 0.44, refDistance: 0.5, maxDistance: 2.8 },
  Beeps2ShortLight1: { path: "assets/sounds/interaction/Beeps2ShortLight1.ogg", volume: 0.44, refDistance: 0.5, maxDistance: 2.8 },
  ControlPostAlert1: { path: "assets/sounds/interaction/ControlPostAlert1.ogg", volume: 0.62, refDistance: 0.55, maxDistance: 2.4 },
  ControlPostBuzzLoop1: {
    path: "assets/sounds/machinery/ControlPostBuzzLoop1.ogg",
    loop: true,
    volume: 0.16,
    refDistance: 0.45,
    maxDistance: 2,
    fadeSeconds: 0.35,
  },
  Clock1_loop: {
    path: "assets/sounds/machinery/Clock1_loop.ogg",
    loop: true,
    volume: 0.22,
    refDistance: 0.35,
    maxDistance: 2.4,
    fadeSeconds: 0.25,
  },
  DoorBulk1_Close1: { path: "assets/sounds/interaction/DoorBulk1_Close1.ogg", volume: 0.78 },
  DoorBulk1_LatchCrank1: { path: "assets/sounds/interaction/DoorBulk1_LatchCrank1.ogg", volume: 0.86 },
  DoorBulk1_Open1: { path: "assets/sounds/interaction/DoorBulk1_Open1.ogg", volume: 0.78 },
  DoorPushbar_Close1: { path: "assets/sounds/interaction/DoorPushbar_Close1.ogg", volume: 0.72 },
  DoorPushbar_Open1: { path: "assets/sounds/interaction/DoorPushbar_Open1.ogg", volume: 0.72 },
  Footsteps1_Walk1: { path: "assets/sounds/player/Footsteps1_Walk1.ogg", loop: true, volume: 0.44 },
  FusionCore_Ignite1: { path: "assets/sounds/machinery/FusionCore_Ignite1.ogg", volume: 0.86 },
  FusionCore_Pulse1: { path: "assets/sounds/machinery/FusionCore_Pulse1.ogg", volume: 0.7 },
  FusionCore_Working1: {
    path: "assets/sounds/machinery/FusionCore_Working1.ogg",
    loop: true,
    volume: 0.46,
    fadeSeconds: 1.4,
  },
  LampConstantBuzz1: { path: "assets/sounds/machinery/LampConstantBuzz1.ogg", loop: true, volume: 0.12, refDistance: 0.45, maxDistance: 3.2 },
  LampConstantBuzz2: { path: "assets/sounds/machinery/LampConstantBuzz2.ogg", loop: true, volume: 0.12, refDistance: 0.45, maxDistance: 3.2 },
  LampConstantBuzzBroken1: { path: "assets/sounds/machinery/LampConstantBuzzBroken1.ogg", loop: true, volume: 0.14, refDistance: 0.2, maxDistance: 0.7 },
  LampTurnOn1: { path: "assets/sounds/machinery/LampTurnOn1.ogg", volume: 0.42 },
  MessageEN_Welcome1: { path: "assets/sounds/narration/MessageEN_Welcome1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  MessageEN_WelcomeElevator1: { path: "assets/sounds/narration/MessageEN_WelcomeElevator1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  MessageRU_Welcome1: { path: "assets/sounds/narration/MessageRU_Welcome1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  MessageRU_WelcomeElevator1: { path: "assets/sounds/narration/MessageRU_WelcomeElevator1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  MotorSmall1: { path: "assets/sounds/interaction/MotorSmall1.ogg", volume: 0.56, refDistance: 0.55, maxDistance: 3 },
  Panel1_SfxLoop1: { path: "assets/sounds/machinery/Panel1_SfxLoop1.ogg", loop: true, volume: 0.18 },
  UI_Hint1: { path: "assets/sounds/ui/UI_Hint1.ogg", volume: 0.46 },
  UI_PaperSlide1: { path: "assets/sounds/ui/UI_PaperSlide1.ogg", volume: 0.42 },
  UI_PaperSlide2: { path: "assets/sounds/ui/UI_PaperSlide2.ogg", volume: 0.42 },
  UI_PaperSlide3: { path: "assets/sounds/ui/UI_PaperSlide3.ogg", volume: 0.42 },
  UI_PaperSlide4: { path: "assets/sounds/ui/UI_PaperSlide4.ogg", volume: 0.42 },
};

export const SOUND_GROUPS = {
  panelButtonLight: ["Button_Light1", "Button_Light2", "Button_Light3"],
  mechanicalButton: ["ButtonMechanical1", "ButtonMechanical2", "ButtonMechanical3", "ButtonMechanical4"],
  lampConstantBuzz: ["LampConstantBuzz1", "LampConstantBuzz2"],
  paperSlide: ["UI_PaperSlide1", "UI_PaperSlide2", "UI_PaperSlide3", "UI_PaperSlide4"],
};

export const SOUND_MIX = {
  master: 1,
  ambience: 1,
  interaction: 1,
  machinery: 1,
  narration: 1,
  player: 1,
  ui: 1,
};
