export const SOUND_REGISTRY = {
  Ambience_Cave1: {
    path: "assets/sounds/Ambience_Cave1.mp3",
    loop: true,
    volume: 0.36,
    fadeDistance: 1.6,
  },
  Ambience_CaveWindy1: {
    path: "assets/sounds/Ambience_CaveWindy1.mp3",
    loop: true,
    volume: 0.42,
    fadeDistance: 1.8,
  },
  Button_Light1: { path: "assets/sounds/Button_Light1.mp3", volume: 0.48 },
  Button_Light2: { path: "assets/sounds/Button_Light2.mp3", volume: 0.48 },
  Button_Light3: { path: "assets/sounds/Button_Light3.mp3", volume: 0.48 },
  ButtonMechanical1: { path: "assets/sounds/ButtonMechanical1.mp3", volume: 0.62 },
  ButtonMechanical2: { path: "assets/sounds/ButtonMechanical2.mp3", volume: 0.62 },
  ButtonMechanical3: { path: "assets/sounds/ButtonMechanical3.mp3", volume: 0.62 },
  ButtonMechanical4: { path: "assets/sounds/ButtonMechanical4.mp3", volume: 0.62 },
  DoorBulk1_Close1: { path: "assets/sounds/DoorBulk1_Close1.mp3", volume: 0.78 },
  DoorBulk1_LatchCrank1: { path: "assets/sounds/DoorBulk1_LatchCrank1.mp3", volume: 0.86 },
  DoorBulk1_Open1: { path: "assets/sounds/DoorBulk1_Open1.mp3", volume: 0.78 },
  DoorPushbar_Close1: { path: "assets/sounds/DoorPushbar_Close1.mp3", volume: 0.72 },
  DoorPushbar_Open1: { path: "assets/sounds/DoorPushbar_Open1.mp3", volume: 0.72 },
  Footsteps1_Walk1: { path: "assets/sounds/Footsteps1_Walk1.mp3", loop: true, volume: 0.44 },
  FusionCore_Ignite1: { path: "assets/sounds/FusionCore_Ignite1.mp3", volume: 0.86 },
  FusionCore_Pulse1: { path: "assets/sounds/FusionCore_Pulse1.mp3", volume: 0.7 },
  FusionCore_Working1: {
    path: "assets/sounds/FusionCore_Working1.mp3",
    loop: true,
    volume: 0.46,
    fadeSeconds: 1.4,
  },
  LampConstantBuzz1: { path: "assets/sounds/LampConstantBuzz1.mp3", loop: true, volume: 0.12, refDistance: 0.45, maxDistance: 3.2 },
  LampConstantBuzz2: { path: "assets/sounds/LampConstantBuzz2.mp3", loop: true, volume: 0.12, refDistance: 0.45, maxDistance: 3.2 },
  LampConstantBuzzBroken1: { path: "assets/sounds/LampConstantBuzzBroken1.mp3", loop: true, volume: 0.14, refDistance: 0.2, maxDistance: 0.7 },
  LampTurnOn1: { path: "assets/sounds/LampTurnOn1.mp3", volume: 0.42 },
  MessageEN_Welcome1: { path: "assets/sounds/MessageEN_Welcome1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  MessageRU_Welcome1: { path: "assets/sounds/MessageRU_Welcome1.ogg", volume: 0.9, maxDistance: 3.8, refDistance: 0.7 },
  Panel1_SfxLoop1: { path: "assets/sounds/Panel1_SfxLoop1.mp3", loop: true, volume: 0.18 },
  UI_Hint1: { path: "assets/sounds/UI_Hint1.mp3", volume: 0.46 },
  UI_PaperSlide1: { path: "assets/sounds/UI_PaperSlide1.mp3", volume: 0.42 },
  UI_PaperSlide2: { path: "assets/sounds/UI_PaperSlide2.mp3", volume: 0.42 },
  UI_PaperSlide3: { path: "assets/sounds/UI_PaperSlide3.mp3", volume: 0.42 },
  UI_PaperSlide4: { path: "assets/sounds/UI_PaperSlide4.mp3", volume: 0.42 },
};

export const SOUND_GROUPS = {
  panelButtonLight: ["Button_Light1", "Button_Light2", "Button_Light3"],
  mechanicalButton: ["ButtonMechanical1", "ButtonMechanical2", "ButtonMechanical3", "ButtonMechanical4"],
  lampConstantBuzz: ["LampConstantBuzz1", "LampConstantBuzz2"],
  paperSlide: ["UI_PaperSlide1", "UI_PaperSlide2", "UI_PaperSlide3", "UI_PaperSlide4"],
};
