import * as THREE from "three";
import { POST_PROCESSING_CONFIG } from "./PostProcessingConfig.js?v=body-motion-debug";
import { DEBUG_CONFIG } from "./config/DebugConfig.js?v=body-motion-debug";
import { GLOBAL_SCENE_OVERRIDES } from "./generated/GlobalSceneOverrides.js?v=body-motion-debug";
import { LEVEL_ENVIRONMENTS } from "./levels/LevelRegistry.js?v=body-motion-debug";

function applyLevelMaterialTuning(materials, tuning) {
  Object.entries(tuning ?? {}).forEach(([key, values]) => {
    if (materials[key]) Object.assign(materials[key], values);
  });
  return materials;
}

function applyKnownConfigOverrides(target, overrides) {
  if (!target || !overrides || typeof overrides !== "object") return target;
  Object.entries(overrides).forEach(([key, value]) => {
    if (!(key in target)) return;
    if (value && typeof value === "object" && !Array.isArray(value)
      && target[key] && typeof target[key] === "object" && !Array.isArray(target[key])) {
      applyKnownConfigOverrides(target[key], value);
    } else {
      target[key] = value;
    }
  });
  return target;
}

export const CONFIG = {
  assetPath: "assets/mesh/panel/SM_Panel1.glb",
  playerEyeHeight: 1.45,
  player: {
    spawnPosition: new THREE.Vector3(0, 1.45, 2),
    spawnYawDegrees: 0,
    spawnPitchDegrees: 0,
    collisionRadius: 0.15,
    collisionHeight: 1.7,
    stance: {
      crouchHeight: 1.12,
      crouchEyeHeight: 0.92,
    },
    collision: {
      cameraRadius: 0.12,
      stepHeight: 0.22,
      stepMinWidth: 0.12,
      snapToGround: 0.35,
      controllerOffset: 0.015,
      mass: 75,
      jumpSpeed: 2.3,
      maxSlopeDegrees: 50,
      minSlideDegrees: 55,
      floorNormalThreshold: 0.55,
      show: false,
      position: new THREE.Vector3(0, 0, 0),
    },
  },
  levelEnvironments: LEVEL_ENVIRONMENTS,
  loading: {
    skip: false,
  },
  debug: DEBUG_CONFIG,
  app: {
    firstVisitEmulation: false,
  },
  interaction: {
    maxDistance: 1.85,
    panelMaxDistance: 1.45,
  },
  textureStreaming: {
    fullLoadDelaySeconds: 4,
  },
  camera: {
    fovDegrees: 72,
    zoomFovDegrees: 68,
    zoomDamping: 12,
    mouseSensitivity: 0.0022,
    pitchLimitDegrees: 72,
    leanPitchLimitDegrees: 88,
    walkSpeed: 1.65,
    runSpeed: 2.85,
    crouchSpeed: 0.85,
    operatorMovement: {
      acceleration: 7,
      deceleration: 12,
      zoomSpeedMultiplier: 0.22,
      zoomSensitivityMultiplier: 0.88,
      leanForward: 0.26,
      leanDown: 0.025,
      leanDamping: 4,
      bodyRig: {
        freeHeadYawDegrees: 28,
        stationaryBodyTurnFrequency: 2.2,
        movingBodyTurnFrequency: 4.2,
        fastBodyTurnFrequency: 6,
        stationaryTurnStepDegrees: 17,
        stationaryTurnStepInterval: 0.34,
        walkStrideLength: 1.2,
        runStrideLength: 1.55,
        crouchStrideLength: 0.86,
        walkReferenceSpeed: 1.65,
        strafeTranslation: 0.015,
        strafeRollDegrees: 1.5,
        strafeSpringFrequency: 7.2,
        strafeSpringDamping: 0.62,
        forwardAccelerationScale: 0.0021,
        forwardWeightLimit: 0.024,
        forwardWeightFrequency: 6.2,
        forwardWeightDamping: 0.72,
        forwardWeightPitchDegreesPerMeter: 24,
        lookAngularVelocityLimit: 7,
        lookAngularVelocityForFullSway: 4.5,
        lookReactionFrequency: 8,
        lookReactionDamping: 0.58,
        lookYawTranslation: 0.012,
        lookYawRollDegrees: 1.25,
        lookPitchReactionDegrees: 0.65,
        headYawTranslation: 0.0045,
        headYawRollDegrees: 0.32,
        bodyGaitSide: 0.019,
        bodyGaitVertical: 0.02,
        cameraGaitSide: 0.014,
        cameraGaitVertical: 0.016,
        cameraGaitRollDegrees: 0.9,
        cameraGaitPitchDegrees: 0.58,
        heldGaitSide: 0.025,
        heldGaitVertical: 0.027,
        heldGaitRollDegrees: 1.45,
        heldGaitPitchDegrees: 1.05,
        heldMassScale: 1.45,
        walkHeelCompressionImpulse: 0.045,
        runHeelCompressionImpulse: 0.07,
        turnFootCompressionImpulse: 0.012,
        turnWeightImpulse: 0.018,
        heelSpringFrequency: 7.5,
        turnWeightFrequency: 6.5,
        stanceSpringFrequency: 4.6,
        stepVerticalStabilization: 0.72,
        verticalRecoveryFrequency: 5.4,
        landingImpulseScale: 0.018,
        landingImpulseLimit: 0.13,
        heldTurnYawScale: 0.018,
        heldIdleSideAmplitude: 0.0012,
        heldIdleVerticalAmplitude: 0.0008,
        heldIdleRollDegrees: 0.12,
        heldIdlePitchDegrees: 0.09,
        heldIdleSwayFrequencyHz: 0.22,
        heldIdleTremorTranslation: 0.00015,
        heldIdleTremorDegrees: 0.025,
        heldIdleTremorFrequencyHz: 7.2,
      },
    },
    noclip: {
      enabled: false,
      speed: 3.5,
      minSpeed: 0.25,
      maxSpeed: 30,
      wheelStep: 0.35,
    },
    menuView: {
      position: new THREE.Vector3(4.4, 0.95, -1.85),
      rotationDegrees: new THREE.Vector3(20.3, 55.9, 0),
      fovDegrees: 55,
      roomLightsOn: false,
      pointerLook: {
        enabled: true,
        yawDegrees: 1.5,
        pitchDegrees: 0.8,
        damping: 5,
      },
    },
  },
  panel: {
    position: new THREE.Vector3(0, 0, 0),
    rotation: new THREE.Euler(0, 0, 0),
    scale: new THREE.Vector3(1, 1, 1),
    placeholderColor: "#365247",
    maps: {
      preview: {
        baseColor: "assets/runtime-textures/T_Panel1_BaseColor_Critical_Preview_1024_ETC1S.ktx2",
        normal: "assets/runtime-textures/T_Panel1_Normal_Critical_Preview_1024_ETC1S.ktx2",
        orm: "assets/runtime-textures/T_Panel1_OcclusionRoughnessMetallic_Critical_Preview_1024_ETC1S.ktx2",
      },
      full: {
        baseColor: "assets/runtime-textures/T_Panel1_BaseColor_Critical_Full_ETC1S.ktx2",
        normal: "assets/runtime-textures/T_Panel1_Normal_Critical_Full_ETC1S.ktx2",
        orm: "assets/runtime-textures/T_Panel1_OcclusionRoughnessMetallic_Critical_Full_ETC1S.ktx2",
      },
    },
  },
  interior: {
    position: new THREE.Vector3(0, 0, 0),
    rotation: new THREE.Euler(0, 0, 0),
    scale: new THREE.Vector3(1, 1, 1),
    decals: null,
    material: {
      color: "#7e807e",
      roughness: 0.82,
      metalness: 0,
    },
    specialMaterials: applyLevelMaterialTuning({
      briefPaper: {
        materialNames: ["M_Brief", "M_Brief.001"],
        meshNames: ["SM_Brief1"],
        color: "#aaa69d",
        roughness: 0.82,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
        alphaTest: 0.5,
        side: THREE.DoubleSide,
        castShadow: true,
        receiveShadow: true,
      },
      lampDome1Bulb: {
        materialNames: ["M_EmissBulb1"],
        meshNames: ["SM_LampDome1_Bulb"],
        color: "#ffffff",
        roughness: 0.35,
        metalness: 0,
        emissive: "#fff0cf",
        emissiveIntensity: 6,
        castShadow: false,
        receiveShadow: false,
      },
      lamp1: {
        materialNames: ["M_Lamp1"],
        meshNames: ["SM_Lamp1", "SM_Lamp1_1", "SM_Lamp1_2", "SM_Lamp1001"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Preview_512_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Preview_512_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Preview_512_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ffffff",
        emissiveIntensity: 2.35,
        roomLightControlled: true,
      },
      doorLamp1: {
        meshNames: ["SM_Door1_Lamp", "SM_Door1_Handle", "SM_Door1_Panel", "SM_Door1_Frame"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_DoorLamp1_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp1_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp1_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp1_Emissive_Interactive_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_DoorLamp1_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp1_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp1_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp1_Emissive_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ff0000",
        emissiveIntensity: 5.5,
      },
      bricks1: {
        materialNames: ["M_InteriorCab"],
        meshNames: ["SM_Interior1"],
        namePrefixes: ["SM_Interior1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Bricks1Old_BaseColor_Background_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Bricks1Old_Normal_Background_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Bricks1Old_ORM_Background_Preview_1024_ETC1S.ktx2",
            mask: "assets/runtime-textures/T_Interior1_Mask_Background_Preview_1024.png",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Bricks1Old_BaseColor_Background_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Bricks1Old_Normal_Background_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Bricks1Old_ORM_Background_Full_ETC1S.ktx2",
            mask: "assets/runtime-textures/T_Interior1_Mask_Background_Full_ETC1S.ktx2",
          },
        },
        color: "#fdfffe",
        roughness: 1,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
        textureRepeat: 6.8,
        maskOverlay: {
          debugView: false,
          red: { color: "#804800", opacity: 0.4, intensity: 1, threshold: 0, softness: 1, blend: "multiply" },
          green: { color: "#5e5343", opacity: 0.7, intensity: 1.0, threshold: 0, softness: 1, blend: "multiply" },
          blue: { color: "#1a1a1a", opacity: 0.8, intensity: 1, threshold: 0, softness: 1, blend: "multiply" },
        },
      },
      details1: {
        materialNames: ["M_Details1"],
        namePrefixes: ["SM_Details1", "SM_Details_", "SM_Fan"],
        meshNames: [
          "SM_Fan",
          "SM_Details1_1",
          "SM_Details1_2",
          "SM_Details1_3",
          "SM_Details1_4",
          "SM_Details1_6",
          "SM_Details1_7",
          "SM_Details1_8",
          "SM_Details1_9",
          "SM_Details1_10",
          "SM_Details1_11",
          "SM_Details_LightButton1",
        ],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Details1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Details1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Details1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Details1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Details1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Details1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1.2,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      pipes1: {
        materialNames: ["M_Pipes1", "M_Pipes1.001"],
        namePrefixes: ["SM_Pipes1", "SM_Cable"],
        meshNames: [
          "SM_Pipes1_1",
          "SM_Pipes1_2",
          "SM_Pipes1_3",
          "SM_Pipes1_4",
          "SM_Pipes1_5",
          "SM_Pipes1_6",
          "SM_Pipes1_7",
          "SM_Pipes1_8",
          "SM_Pipes1_9",
          "SM_Pipes1_10",
          "SM_Pipes1_11",
          "SM_Pipes1_12",
        ],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Pipes1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Pipes1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Pipes1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Pipes1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Pipes1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Pipes1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      beams1: {
        materialNames: ["M_Beams", "M_Beams.001", "M_Beams.002"],
        namePrefixes: ["SM_Beams", "M_Beams"],
        meshNames: ["SM_Beams_1", "SM_Beams_2", "SM_Beams_PipeAttachemts1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Beams1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Beams1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Beams1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Beams1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Beams1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Beams1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      trimConcrete1: {
        materialNames: ["M_TrimConcrete1", "M_TrimConcrete1.001", "M_TrimConcrete1.002", "M_TrimConcrete1.003"],
        namePrefixes: ["SM_TrimConcrete"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_TrimConcrete1_BaseColor_Background_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_TrimConcrete1_Normal_Background_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_TrimConcrete1_OcclusionRoughnessMetallic_Background_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_TrimConcrete1_BaseColor_Background_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_TrimConcrete1_Normal_Background_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_TrimConcrete1_OcclusionRoughnessMetallic_Background_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      rock1: {
        materialNames: ["M_Rock1"],
        namePrefixes: ["SM_Rock", "Rock"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Rock1_BaseColor_Background_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Rock1_Normal_Background_Preview_1024_ETC1S.ktx2",
            roughness: "assets/runtime-textures/T_Rock1_Roughness_Background_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Rock1_BaseColor_Background_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Rock1_Normal_Background_Full_ETC1S.ktx2",
            roughness: "assets/runtime-textures/T_Rock1_Roughness_Background_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      radio1: {
        materialNames: ["M_Radio1"],
        namePrefixes: ["SM_Radio1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Radio1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Radio1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Radio1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Radio1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Radio1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Radio1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      radioLamp: {
        meshNames: ["SM_Radio1_Lamp"],
        color: "#3a0503",
        roughness: 0.55,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ff1408",
        emissiveIntensity: 0,
        castShadow: false,
        receiveShadow: false,
      },
      trimTiles1: {
        materialNames: ["M_TrimTiles1"],
        namePrefixes: ["SM_TrimTiles1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Trim2Tiles1_BaseColor_Background_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Trim2Tiles1_Normal_Background_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Trim2Tiles1_OcclusionRoughnessMetallic_Background_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Trim2Tiles1_BaseColor_Background_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Trim2Tiles1_Normal_Background_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Trim2Tiles1_OcclusionRoughnessMetallic_Background_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      door2: {
        materialNames: ["M_Door2", "M_Door2.001"],
        namePrefixes: ["SM_Door2"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Door2_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Door2_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Door2_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Door2_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Door2_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Door2_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      door2Glass: {
        meshNames: ["SM_Door2_Glass"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Door2_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Door2_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Door2_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Door2_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Door2_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Door2_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 0.48,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
        transparent: true,
        opacity: 0.32,
        depthWrite: false,
        side: THREE.DoubleSide,
        castShadow: false,
        receiveShadow: false,
      },
      barrier1: {
        materialNames: ["M_Barrier1", "M_Barrier1.001"],
        namePrefixes: ["SM_Barrier1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Barrier1_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Barrier1_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Barrier1_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Barrier1_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Barrier1_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Barrier1_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      controlPost1: {
        materialNames: ["M_ControlPost1", "M_ControlPost1.001"],
        namePrefixes: ["SM_ControlPost1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_ControlPost1_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_ControlPost1_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_ControlPost1_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_ControlPost1_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_ControlPost1_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_ControlPost1_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      desk1: {
        materialNames: ["M_Desk1", "M_Desk1.001"],
        namePrefixes: ["SM_Desk1", "SM_Chair1", "SM_LampDesk1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Desk1_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Desk1_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Desk1_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Desk1_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Desk1_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Desk1_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      lampDesk1Bulb: {
        meshNames: ["SM_LampDesk1_Bulb"],
        color: "#fff4d6",
        roughness: 0.34,
        metalness: 0,
        emissive: "#fff0c7",
        emissiveIntensity: 5,
        castShadow: false,
        receiveShadow: false,
      },
      posters1: {
        materialNames: ["M_Posters1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Posters1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Posters1_BaseColor_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 0.82,
        metalness: 0,
        emissive: "#000000",
        emissiveIntensity: 0,
        alphaTest: 0.5,
        side: THREE.DoubleSide,
        castShadow: true,
        receiveShadow: true,
      },
      signs1: {
        materialNames: ["M_Signs1"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Signs1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Signs1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Signs1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Signs1_Emissive_Secondary_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Signs1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Signs1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Signs1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Signs1_Emissive_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ffffff",
        emissiveIntensity: 1,
      },
      doorLamp2: {
        materialNames: ["M_DoorLamp2"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_DoorLamp2_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp2_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp2_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp2_Emissive_Interactive_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_DoorLamp2_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp2_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp2_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp2_Emissive_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ff1b0a",
        emissiveIntensity: 4,
      },
      clock1: {
        materialNames: ["M_Clock1"],
        meshNames: [
          "SM_Clock1_Base",
          "SM_Clock1_ArrowSeconds",
          "SM_Clock1_ArrowMinutes",
          "SM_Clock1_ArrowHours",
        ],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Clock1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Clock1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Clock1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Clock1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Clock1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Clock1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      clock1Glass: {
        meshNames: ["SM_Clock1_Glass"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Clock1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Clock1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Clock1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Clock1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Clock1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Clock1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 0.62,
        metalness: 0,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
        transparent: true,
        opacity: 0.42,
        depthWrite: false,
        side: THREE.DoubleSide,
        castShadow: false,
        receiveShadow: false,
      },
    }, GLOBAL_SCENE_OVERRIDES.materials),
    lightToggleButton: {
      meshNames: ["SM_Details_LightButton1"],
      namePrefixes: ["SM_Details_LightButton1"],
      label: "ROOM LIGHTS",
      initialOn: true,
      hitRadius: 0.09,
      pressAxis: "x",
      pressDistance: -0.018,
      pressSpeed: 4,
      fadeSeconds: 0.3,
      flickerSeconds: 1.28,
      flickerFrequency: 22,
    },
    bulkheadExit: {
      meshName: "SM_Door1_Handle",
      label: "BULKHEAD HANDLE",
      rotationAxis: "x",
      maxInteractionDistance: 2.2,
      lockedStopDegrees: 20,
      lockedAttemptSeconds: 1.65,
      lockedKnockDegrees: 2.4,
      unlockedTurnDegrees: 270,
      unlockHoldSeconds: 2.8,
      turnJerkDegrees: 2.1,
      turnJerkFrequency: 9,
      returnSeconds: 1.1,
    },
    fans: {},
  },
  needleAnimation: {
    minDegrees: 30,
    maxDegrees: -210,
    inactiveDegrees: 30,
    activeDegrees: -210,
    speedDegreesPerSecond: {
      min: 30,
      max: 230,
    },
    speedRetargetInterval: 1.18,
    jitterDegrees: 1.2,
    jitterFrequency: 432,
    jitterRetargetInterval: 0.16,
    overshootDegrees: 4,
  },
  controls: {
    wheelPercentPerDelta: 0.025,
    wheelMaxStepPercent: 2.5,
    knobDialDegrees: 360,
    knobValue0DialPercent: 85,
    knobValue100DialPercent: 15,
    knobRotationAxis: "y",
    labelYOffset: 0.1,
    knobs: {
      Control_Knob_FuelInjection: {
        label: "FUEL INJECTION",
        initialPercent: 35,
      },
      Control_Knob_MagneticField: {
        label: "MAGNETIC FIELD",
        initialPercent: 55,
      },
      Control_Knob_CoolantFlow: {
        label: "COOLANT FLOW",
        initialPercent: 40,
      },
    },
    buttons: {
      Control_Btn_Test: {
        label: "INDICATOR TEST",
        action: "indicatorTest",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Control_Btn_Start: {
        label: "START CORE",
        action: "start",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Control_Btn_Reset: {
        label: "PULSE",
        action: "pulse",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Test: {
        label: "INDICATOR TEST",
        action: "indicatorTest",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Start: {
        label: "START CORE",
        action: "start",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Reset: {
        label: "PULSE",
        action: "pulse",
        pressAxis: "y",
        pressDistance: -0.018,
        pressSpeed: 18,
      },
      Control_Btn_Vent: {
        label: "EMERGENCY VENT / PURGE",
        action: "vent",
        pressAxis: "y",
        pressDistance: -0.025,
        pressSpeed: 18,
      },
    },
  },



  room: {
    width: 12,
    depth: 12,
    height: 4,
    floorVisible: false,
  },
  world: {
    backgroundColor: "#080b0d",
    fogColor: "#080b0d",
    fogNear: 1,
    fogFar: 10,
  },
  lighting: {
    ambientSky: "#9fb6c7",
    ambientGround: "#101010",
    ambientIntensity: 0,
    photometricPointLights: {
      maxLights: 4,
      maxProfiles: 2,
      selectionRadius: 20,
      selectionHysteresis: 2,
      transitionSeconds: 0.6,
    },
    pointLightPool: {
      fixtureRadius: 10,
      simpleRadius: 20,
      selectionHysteresis: 2,
      transitionSeconds: 0.5,
      zoneAdjacencyMargin: 0.35,
      zoneExitPadding: 0.6,
    },
    pointLights: {},
    fixtures: {},
  },
  sceneDebug: {
    enabled: true,
    levelId: "global",
    startClosed: true,
    toggleSequence: "debug3",
  },
  feedback: {
    startup: {
      duration: 3.2,
      operationalDelaySeconds: 18,
      roomDimSeconds: 18,
      roomMinLightFactor: 0.5,
      roomCameraShake: 0.00065,
      blackoutSeconds: 0.28,
      lampFrequency: 18,
      needleJitterDegrees: 40,
      cameraShake: 0,
      fluorescentStartup: {
        warmupSeconds: [0.12, 0.32],
        attemptCount: [3, 6],
        attemptOnSeconds: [0.055, 0.16],
        attemptOffSeconds: [0.045, 0.13],
        dimFactor: [0.04, 0.18],
        strikeFactor: [0.42, 0.92],
        settleSeconds: [0.16, 0.34],
        finalOvershoot: [1, 1.06],
      },
    },
    roomLightSwitch: {
      lightFadeOutSeconds: 0.14,
      afterglowSeconds: 3,
      afterglowInitialFactor: 0.2,
      afterglowExponent: 2.4,
      abuseWindowSeconds: 4,
      abuseToggleCount: 6,
      starterFaultSeconds: 20,
      faultMinimumFactor: 0.025,
      faultMaximumFactor: 0.3,
    },
    longTermLightFlicker: {
      enabled: true,
      minIntervalSeconds: 20,
      maxIntervalSeconds: 36,
      durationSeconds: [0.42, 1.65],
      minFactor: [0.04, 0.3],
      emissiveExponent: 2,
      retryChance: 0.85,
      pulseCount: [4, 9],
    },
    thermalEmergency: {
      lampFlickerFrequency: 16,
      cameraShake: 0.0035,
      bloomBoost: 0.42,
      chromaticBoost: 0.0045,
    },
    outputLow: {
      lightFlicker: 0.1,
      lampFlickerFrequency: 10,
      cameraShake: 0,
    },
    ignitionPulse: {
      duration: 0.72,
      cameraShake: 0.018,
      needleKickDegrees: 14,
    },
    startupFault: {
      resetSeconds: 20,
      greenLampSeconds: 0.55,
      redLampSeconds: 2,
      needleSweepUpSeconds: 0.38,
      needleSweepHoldSeconds: 0.42,
      needleSweepDownSeconds: 0.62,
      sweepGaugeKeys: ["plasmaTemp", "powerOutput"],
      cameraShake: 0.006,
    },
    panelIndicators: {
      amberEmissiveIntensity: 0.35,
      greenEmissiveIntensity: 0.35,
      redEmissiveIntensity: 0.55,
      statusScreenBrightness: 0.4,
    },
    terminal: {
      instrumentShutdownSeconds: 2.4,
      emergencyEffectFadeSeconds: 1.6,
      destroyedBlackoutSeconds: 1.4,
      emergencyLightSettleSeconds: 0.45,
      resultsHoldSeconds: 10,
      completeLightFactor: 0.82,
      failedLightFactor: 0.55,
      destroyedLightFactor: 1,
    },
    indicatorTest: {
      duration: 10,
      lampFrequency: 9,
    },
  },
  shadows: {
    defaultQuality: "min",
    type: THREE.PCFSoftShadowMap,
    castNeedleShadows: false,
    presets: {
      off: { enabled: false, mapSize: 0 },
      min: { enabled: true, heroOnly: true, mapSize: 512 },
      med: { enabled: true, mapSize: 1024 },
      max: { enabled: true, mapSize: 2048 },
    },
  },
  postProcessing: POST_PROCESSING_CONFIG,
};

applyKnownConfigOverrides(CONFIG.camera, GLOBAL_SCENE_OVERRIDES.camera);
applyKnownConfigOverrides(CONFIG.lighting, GLOBAL_SCENE_OVERRIDES.lighting);

export const MATERIAL_COLORS = {
  wall: "#252d32",
  floor: "#171c20",
  trim: "#5d6b73",
  lampOff: "#171717",
  lampOffEmissive: "#000000",
  lampAmber: "#ffcc47",
  lampAmberEmissive: "#ffb000",
  lampGreen: "#55ff91",
  lampGreenEmissive: "#19ff6c",
  lampRed: "#ff5555",
  lampRedEmissive: "#ff1f1f",
  needle: "#ff5a58",
  needleEmissive: "#df840d",
  button: "#8e2621",
  buttonEmissive: "#290000",
  buttonOn: "#ff4e42",
  buttonOnEmissive: "#ff2b1f",
};
