import * as THREE from "three";

export const CONFIG = {
  assetPath: "assets/Panel1.glb",
  playerEyeHeight: 1.45,
  player: {
    spawnPosition: new THREE.Vector3(0, 1.45, 2),
    spawnYawDegrees: 0,
    spawnPitchDegrees: 0,
  },
  loading: {
    skip: false,
  },
  textureStreaming: {
    fullLoadDelaySeconds: 4,
  },
  camera: {
    fovDegrees: 72,
    zoomFovDegrees: 68,
    zoomDamping: 12,
    mouseSensitivity: 0.0022,
    pitchLimitDegrees: 72,
    leanPitchLimitDegrees: 88,
    walkSpeed: 1.8,
    runSpeed: 4.2,
    operatorMovement: {
      acceleration: 7,
      deceleration: 12,
      zoomSpeedMultiplier: 0.22,
      zoomSensitivityMultiplier: 0.88,
      headBobAmplitude: 0.018,
      headBobSway: 0.009,
      headBobFrequency: 4.5,
      leanForward: 0.26,
      leanDown: 0.025,
      leanDamping: 4,
    },
    noclip: {
      enabled: false,
      speed: 3.5,
      minSpeed: 0.25,
      maxSpeed: 30,
      wheelStep: 0.35,
    },
  },
  panel: {
    position: new THREE.Vector3(0, 0, 0),
    rotation: new THREE.Euler(0, 0, 0),
    scale: new THREE.Vector3(1, 1, 1),
    placeholderColor: "#365247",
    maps: {
      preview: {
        baseColor: "assets/runtime-textures/T_Panel1_BaseColor_Critical_Preview_1024_ETC1S.ktx2",
        normal: "assets/runtime-textures/T_Panel1_Normal_Critical_Preview_1024_ETC1S.ktx2",
        orm: "assets/runtime-textures/T_Panel1_OcclusionRoughnessMetallic_Critical_Preview_1024_ETC1S.ktx2",
      },
      full: {
        baseColor: "assets/runtime-textures/T_Panel1_BaseColor_Critical_Full_ETC1S.ktx2",
        normal: "assets/runtime-textures/T_Panel1_Normal_Critical_Full_ETC1S.ktx2",
        orm: "assets/runtime-textures/T_Panel1_OcclusionRoughnessMetallic_Critical_Full_ETC1S.ktx2",
      },
    },
  },
  interior: {
    assetPath: "assets/Interior1_Panel1.glb",
    position: new THREE.Vector3(0, 0, 0),
    rotation: new THREE.Euler(0, 0, 0),
    scale: new THREE.Vector3(1, 1, 1),
    material: {
      color: "#7e807e",
      roughness: 0.82,
      metalness: 0,
    },
    specialMaterials: {
      lamp1: {
        meshNames: ["SM_Lamp1", "SM_Lamp1_1", "SM_Lamp1001"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Preview_512_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Preview_512_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Preview_512_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ffffff",
        emissiveIntensity: 2.35,
        roomLightControlled: true,
      },
      lamp1_2: {
        meshNames: ["SM_Lamp1_2"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Preview_512_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Preview_512_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Preview_512_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Lamp1_BaseColor_Critical_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Lamp1_Normal_Critical_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Lamp1_OcclusionRoughnessMetallic_Critical_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_Lamp1_Emissive_Critical_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ffffff",
        emissiveIntensity: 2.35,
        roomLightControlled: true,
      },
      doorLamp1: {
        meshNames: ["SM_Door1_Lamp", "SM_Door1_Handle", "SM_Door1_Panel", "SM_Door1_Frame"],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_DoorLamp1_BaseColor_Interactive_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp1_Normal_Interactive_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp1_OcclusionRoughnessMetallic_Interactive_Preview_1024_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp1_Emissive_Interactive_Preview_512_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_DoorLamp1_BaseColor_Interactive_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_DoorLamp1_Normal_Interactive_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_DoorLamp1_OcclusionRoughnessMetallic_Interactive_Full_ETC1S.ktx2",
            emissive: "assets/runtime-textures/T_DoorLamp1_Emissive_Interactive_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#ff0000",
        emissiveIntensity: 5.5,
      },
      Interior1: {
        meshNames: [
          "SM_Interior1",
          "SM_Beams1",
          "SM_Piping1",
          "SM_Piping2",
          "SM_TubeBig1",
          "SM_TubeBig1_Attachment1",
          "SM_TubeBig1_Attachment2",
        ],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Interior1_BaseColor_Background_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Interior1_Normal_Background_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Interior1_OcclusionRoughnessMetallic_Background_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Interior1_BaseColor_Background_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Interior1_Normal_Background_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Interior1_OcclusionRoughnessMetallic_Background_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
      details1: {
        meshNames: [
          "SM_InteriorRailings1",
          "SM_FanFrame",
          "SM_Fan",
          "SM_Cables_Attachment3",
          "SM_Cables_Attachment2",
          "SM_Cables_Attachment1",
          "SM_Cables4",
          "SM_Cables3",
          "SM_Cables2",
          "SM_Cables1",
          "cable004",
          "cable009",
          "cable014",
          "SM_ButtonBox_Button1",
          "SM_ButtonBox1",
        ],
        maps: {
          preview: {
            baseColor: "assets/runtime-textures/T_Details1_BaseColor_Secondary_Preview_1024_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Details1_Normal_Secondary_Preview_1024_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Details1_OcclusionRoughnessMetallic_Secondary_Preview_1024_ETC1S.ktx2",
          },
          full: {
            baseColor: "assets/runtime-textures/T_Details1_BaseColor_Secondary_Full_ETC1S.ktx2",
            normal: "assets/runtime-textures/T_Details1_Normal_Secondary_Full_ETC1S.ktx2",
            orm: "assets/runtime-textures/T_Details1_OcclusionRoughnessMetallic_Secondary_Full_ETC1S.ktx2",
          },
        },
        color: "#ffffff",
        roughness: 1,
        metalness: 1,
        normalScale: 1,
        aoMapIntensity: 1,
        emissive: "#000000",
        emissiveIntensity: 0,
      },
    },
    lightToggleButton: {
      meshNames: ["SM_ButtonBox_Button1", "Cube.172"],
      label: "ROOM LIGHTS",
      initialOn: true,
      hitRadius: 0.09,
      pressAxis: "x",
      pressDistance: -0.018,
      pressSpeed: 4,
      fadeSeconds: 0.3,
      flickerSeconds: 1.28,
      flickerFrequency: 22,
    },
    fans: {
      SM_Fan: {
        enabled: true,
        axis: "y",
        speedDegreesPerSecond: 820,
      },
    },
  },
  needleAnimation: {
    minDegrees: 30,
    maxDegrees: -210,
    inactiveDegrees: 30,
    activeDegrees: -210,
    speedDegreesPerSecond: {
      min: 30,
      max: 230,
    },
    speedRetargetInterval: 1.18,
    jitterDegrees: 1.2,
    jitterFrequency: 432,
    jitterRetargetInterval: 0.16,
    overshootDegrees: 4,
  },
  controls: {
    wheelPercentPerDelta: 0.025,
    wheelMaxStepPercent: 2.5,
    knobRotationDegrees: 360,
    knobRotationAxis: "y",
    labelYOffset: 0.1,
    knobs: {
      Control_Knob_FuelInjection: {
        label: "FUEL INJECTION",
        initialPercent: 35,
      },
      Control_Knob_MagneticField: {
        label: "MAGNETIC FIELD",
        initialPercent: 55,
      },
      Control_Knob_CoolantFlow: {
        label: "COOLANT FLOW",
        initialPercent: 40,
      },
    },
    buttons: {
      Control_Btn_Test: {
        label: "INDICATOR TEST",
        action: "indicatorTest",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Control_Btn_Start: {
        label: "START CORE",
        action: "start",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Control_Btn_Reset: {
        label: "RESET CORE",
        action: "reset",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Test: {
        label: "INDICATOR TEST",
        action: "indicatorTest",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Start: {
        label: "START CORE",
        action: "start",
        pressAxis: "y",
        pressDistance: -0.006,
        pressSpeed: 18,
      },
      Buttun_Reset: {
        label: "RESET CORE",
        action: "reset",
        pressAxis: "y",
        pressDistance: -0.018,
        pressSpeed: 18,
      },
      Control_Btn_Vent: {
        label: "EMERGENCY VENT / PURGE",
        action: "vent",
        pressAxis: "y",
        pressDistance: -0.025,
        pressSpeed: 18,
      },
    },
  },

// operatorGameDebug.listNeedles()
// operatorGameDebug.setNeedleRotation(0, "x", 45)
// operatorGameDebug.setNeedleRotation(0, "y", 45)
// operatorGameDebug.setNeedleRotation(0, "z", 45)
// operatorGameDebug.getObjectTransform("GaugeSmall_Arrow_TargetOutput")
// operatorGameDebug.listObjects("Arrow")
// operatorGameDebug.findObject("GaugeSmall_Arrow_TargetOutput")
// operatorGameDebug.resumeNeedles()
// operatorGameDebug.startGame()
// operatorGameDebug.resetGame()
//window.operatorGameDebug.getPerformance()


  room: {
    width: 12,
    depth: 12,
    height: 4,
    floorVisible: false,
  },
  world: {
    backgroundColor: "#080b0d",
    fogColor: "#080b0d",
    fogNear: 1,
    fogFar: 10,
  },
  lighting: {
    ambientSky: "#9fb6c7",
    ambientGround: "#101010",
    ambientIntensity: 0.03,
    pointLights: {
      SM_Lamp1_2_Light: {
        color: "#ffffff",
        intensity: 1.3,
        roomLightControlled: true,
        distance: 5,
        decay: 1,
        position: new THREE.Vector3(0.01, 1.91, 0.66),
        castShadow: true,
        shadowMapSize: 128,
        shadowBias: 0.0006,
        shadowNormalBias: 0.035,
        shadowNear: 0.1,
        shadowFar: 9,
      },
      fill: {
        color: "#87b1ff",
        intensity: 0.2,
        roomLightControlled: false,
        distance: 6,
        decay: 0.4,
        position: new THREE.Vector3(0.64, 2.03, 0.45),
        castShadow: false,
        shadowMapSize: 512,
        shadowBias: -0.0005,
        shadowNormalBias: 0.03,
        shadowNear: 0.1,
        shadowFar: 7,
      },
      LampDoor1: {
        color: "#ff0000",
        intensity: 0.2,
        distance: 3,
        decay: 1,
        position: new THREE.Vector3(-0.01, 1.99, 2.31),
        castShadow: false,
        shadowMapSize: 512,
        shadowBias: -0.0006,
        shadowNormalBias: 0.035,
        shadowNear: 0.1,
        shadowFar: 9,
      },
    },
    fixtures: {
      SM_Lamp1_2: {
        lightNames: ["SM_Lamp1_2_Light"],
        materialKeys: ["lamp1_2"],
      }
      // roomFill: {
      //   lightNames: ["fill"],
      //   materialKeys: ["lamp1"],
      // },
    },
  },
  feedback: {
    startup: {
      duration: 3.2,
      blackoutSeconds: 0.28,
      lampFrequency: 18,
      needleJitterDegrees: 40,
      cameraShake: 0.004,
      tubeOnPattern: [
        { time: 0, factor: 0 },
        { time: 0.32, factor: 0 },
        { time: 0.38, factor: 0.9 },
        { time: 0.43, factor: 0.06 },
        { time: 0.54, factor: 1.08 },
        { time: 0.62, factor: 0.16 },
        { time: 0.78, factor: 0.82 },
        { time: 0.93, factor: 0.28 },
        { time: 1.18, factor: 1 },
      ],
    },
    longTermLightFlicker: {
      enabled: true,
      minIntervalSeconds: 20,
      maxIntervalSeconds: 60,
      durationSeconds: [0.28, 3.42],
      minFactor: [0.1, 1.2],
      retryChance: 0.85,
      pulseCount: [1, 5],
    },
    thermalEmergency: {
      lampFlickerFrequency: 16,
      cameraShake: 0.0035,
      bloomBoost: 0.42,
      chromaticBoost: 0.0045,
    },
    outputLow: {
      lightFlicker: 0.1,
      lampFlickerFrequency: 10,
      cameraShake: 0,
    },
    indicatorTest: {
      duration: 3,
      lampFrequency: 9,
    },
  },
  shadows: {
    enabled: true,
    type: THREE.PCFSoftShadowMap,
  },
  postProcessing: {
    enabled: true,
    gtao: {
      enabled: false,
      blendIntensity: 0.8,
      radius: 0.42,
      distanceExponent: 1.7,
      thickness: 0.85,
      distanceFallOff: 1,
      scale: 2,
      samples: 16,
      denoiseRadius: 2,
      denoiseSamples: 8,
    },
    bloom: {
      enabled: true,
      strength: 0.28,
      radius: 0.62,
      threshold: 0.18,
    },
    chromaticAberration: {
      enabled: true,
      amount: 0.0028,
    },
  },
};

export const MATERIAL_COLORS = {
  wall: "#252d32",
  floor: "#171c20",
  trim: "#5d6b73",
  lampOff: "#171717",
  lampOffEmissive: "#000000",
  lampAmber: "#ffcc47",
  lampAmberEmissive: "#ffb000",
  lampGreen: "#55ff91",
  lampGreenEmissive: "#19ff6c",
  lampRed: "#ff5555",
  lampRedEmissive: "#ff1f1f",
  needle: "#ff5a58",
  needleEmissive: "#df840d",
  button: "#8e2621",
  buttonEmissive: "#290000",
  buttonOn: "#ff4e42",
  buttonOnEmissive: "#ff2b1f",
};
